### ISSUE TITLE
[DNC] Request: Standard Step Closed Position Feature

### ISSUE THREAD

**Issue by ghost** [MKhayle/XIVComboExpanded#159]
Replaces Standard Step with Closed Position when you do not have Closed Position active to remind you to use it before pulling.

**Comment by daemitus** [comment]
Possible, but we'd want to make sure you're in a group or duty. 

BoundByDuty could cause issues with quests or other garbage. Maybe if the party UI widget is active?

**Comment by Grammernatzi** [comment]
You probably could just check the PartyList.Length. I'm not sure if Chocobos are counted for it, though.

**Comment by MKhayle** [comment]
> You probably could just check the PartyList.Length. I'm not sure if Chocobos are counted for it, though.

I don't know if you ended up doing it, but I'll be considering it with the DT update

**Comment by Grammernatzi** [comment]
Nah, I never did anything like that, so I'd have no idea. But counting the party size could work. Probably a >= 4 check.

**Comment by MKhayle** [comment]
I'd want to try the party list length but I'm afraid fairies/carbuncle may fuck it up
Chocobos can be partner'd so why not

**Comment by Grammernatzi** [comment]
That's why I figured you would check for four or greater. The only way your
party is that big is if you have at least something you can partner.

**Comment by MKhayle** [comment]
this is one of the oldest issues and I'm glad to say that it's been done 👍🏻
