### ISSUE TITLE
[DRK] Blood Weapon to Delerium combo

### ISSUE THREAD

**Issue by BeetleLord** [MKhayle/XIVComboExpanded#184]
Blood Weapon and Delerium both have a 60 second cooldown, and will always be used on cooldown after the opener. In the opener, Blood Weapon comes first prepull, then Delerium a short while later. However, I suspect a great number of lazy players just mash the two buttons together on cooldown because of their shared timer (me).

A feature that compresses Blood Weapon and Delerium into a single button, prioritizing Blood Weapon if both are off cooldown, would work well for both of these types of players. And it would help deal with the button bloat that DRK suffers from.

**Comment by kaedys** [comment]
This issue can now be closed, as Delirium is now an upgrade from Blood Weapon and folds in all of the effects of both.
