### ISSUE TITLE
[Enhancement]: CooldownData.cs Refining

### ISSUE THREAD

**Issue by vitharr137** [MKhayle/XIVComboExpanded#217]
Hello,

I've been working on optimizing some of the ways the cooldown data works in the addon, and while I'm not confident enough in it yet to open a real pull, I do want to let you know about the advancements we've discovered in some of the other forks of this project to see if you'd like to use any of them! The main reason currently that I avoid a pull is it seems to mess with other aspects of code that rely on the durations of cooldowns being set to 0 manually in CooldownData.cs

These are used in the CooldownData.cs section, and require:
```using FFXIVClientStructs.FFXIV.Client.Game```

The major one is it's been discovered how to get the haste/speed adjusted cooldown of a given actionID:
```
public float BaseCooldown => ActionManager.GetAdjustedRecastTime(ActionType.Spell, this.ActionID) / 1000f;

public float TotalBaseCooldown
{
    get
    {
        var (cur, max) = Service.ComboCache.GetMaxCharges(this.ActionID);

        // Rebase to the current charge count
        var total = this.BaseCooldown / max * cur;

        return total * cur;
    }
}

public float TotalCooldownElapsed => this.cooldownElapsed;

public float TotalCooldownRemaining => this.TotalBaseCooldown - this.TotalCooldownElapsed;
```
That line alone has allowed functions such as tracking uptime for combo based rotations like Twin Snakes or Demolish, by using code like such:
```
double gcd = GetCooldown(MNK.Bootshine).BaseCooldown;
double remainingGCD = GetCooldown(MNK.Bootshine).CooldownRemaining;
double rotate = remainingGCD + (gcd * 3);
```
The rotate double can now be used to check if the Twin Snakes or Demolish duration remaining is less than it, providing an easy switch for combos to adjust to

Another set of useful data has been the easy calculation of time until a certain actionID is able to be used after the next usage:
```
public float ChargeCooldownRemaining
{
    get
    {
        var (cur, _) = Service.ComboCache.GetMaxCharges(this.ActionID);

        return this.TotalCooldownRemaining % (this.TotalBaseCooldown / cur);
    }
}

public float RecoveryTime => this.CooldownRemaining + this.BaseCooldown;

public float ChargeRecoveryTime
{
    get
    {
        if ((this.RemainingCharges - 1) >= 0)
        {
            return this.ChargeCooldownRemaining;
        }

        return this.ChargeCooldownRemaining + this.BaseCooldown;
    }
}

public float TotalChargeCooldownRemaining => this.MaxCharges - this.RemainingCharges > 0
        ? this.MaxCharges - this.RemainingCharges == 1
            ? this.ChargeCooldownRemaining
            : (this.BaseCooldown * ((this.MaxCharges - this.RemainingCharges) - 1)) + this.ChargeCooldownRemaining
        : 0;
```

These can assist for timing/reserving charge based actionIDs for certain buff windows, allowing checks to see if the full charge recovery time would occur prior to a given cooldown.

I've uploaded the txt version of the modified CooldownData.cs which contains some commented lines for the functionality, hope you can find some useful additions!

[CooldownData.txt](https://github.com/daemitus/XIVComboPlugin/files/11399889/CooldownData.txt)

**Comment by MKhayle** [comment]
alright, this is a very old issue and it is interesting in some points
I'm sorry I never took the time to acknowledge/delve into it, but I have just tested & updated it to use it in https://github.com/MKhayle/XIVComboExpanded/commit/9373f8fa32fd5cef8d710197e93690efa4479afa

**Comment by MKhayle** [comment]
Monk has been changed significantly since you published this and I am less aiming at optimization than other forks, but this is still very nice to have overall if I need it at some point

Thanks!

**Comment by MKhayle** [comment]
@kaedys idk if you're still interested in this over what you did there, but just in case

**Comment by vitharr137** [comment]
One other place to look at is the IsOnCooldown() and IsOffCooldown() for a sanity check just to see if those are still doing what is intended on line 400+ in CustomCombo.cs. I think what was discussed in the paladin section fixes it, but just for certainty

**Comment by kaedys** [comment]
So, looks like `IsOnCooldown` and `IsOffCooldown` both just call and return `IsCooldown`, `Off` inverting the result first.  So both of those are also fixed by the change I made.

**Comment by kaedys** [comment]
I'm comparing the above snippet to the existing code, though, and I'll see how easily it can be integrated without (hopefully) breaking anything else >.<

**Comment by kaedys** [comment]
Ok, so, I'm super confused by some of the implementations here, both in the original and the updated, and I think it's causing issues for some of the combos.  

* Why is `RemainingCharges` trying to implicitly calculate the charges, rather than just using the `cur` return from `Service.ComboCache.GetMaxCharges(this.ActionID);`?
* Why does `TotalBaseCooldown` multiply by `cur`?  Wouldn't that return _zero_ for the TotalBaseCooldown if all charges on the ability are currently used?  Why isn't it multiplying against `max` instead?
  * Many usages of `TotalBaseCooldown` subsequently divide by `cur`, which as far as I can tell is 100% identical to just using `this.BaseCooldown`.
* Is `var total = this.cooldownTotal / max * cur;` in `CooldownTotal` meant to be `this.cooldownTotal / (max * cur)` or `(this.cooldownTotal / max) * cur`, which is equivalent to `this.cooldownTotal * (cur / max)`?  As written, the latter is what is used, due to C# operator order precedence.
  * Is `cooldownTotal` the cooldown per charge or the cooldown per charge multiplied by the number of charges?  ie. for, say Drill (2 charges, 20s recharge), would this be 20s or 40s?
* I don't even understand what `ChargeRecoveryTime` is supposed to do.  From the code, it appears to return the current remaining cooldown if at least 1 charge is remaining, and the cooldown remaining _plus_ the time to get a charge if it currently has 0 charges.  What use is this meant to serve?

**Comment by vitharr137** [comment]
I do want to preface this with it was coding by trial and error, and I am not a well educated coder in general by any stretch so there is plenty of room for mistakes that I've made along the way, but so far these have been my observations. Most of this is cobbled together from other forks, or directly dragged out of the structs themselves and put into code here in the best way I could (which is not well): 

FFXIV's reverse engineering chains are split between some of Dalamud's intepretations, and the FFXIVClientStructs themselves, and several references to Excel sheets made from the game engine itself. The lines from 14 to 23 in CooldownData.cs are the ones I was having the most problems with in general, especially cooldownTotal, which does seem to return 0 in many more instances than would be logical, and since a majority of already written combos were using those returns, most of CooldownTotal was rather hackedly put together to match logic that was already being used by other forks, such as the very weird bit with return 0 if 0

- `(this.cooldownTotal / max) * cur` is meant to be the result, as in, for and example like Bloodletter for BRD, which has at high levels 3 charges with 15 second recharge times each, a 45second total cooldown, but at lower levels, only 2 charges, for a max of 30, but each function should return a "CooldownTotal" for the charge of 15 seconds each

- cooldownTotal itself seems to return a timeline-style full value, taking the example of Bloodletter from above, it would be 45 seconds returned for 3 charges of Bloodletter, 15 seconds each. I haven't verified if newer implementations have better calculated today, but at the time, I was struggling with the calculation returning 45 for example, when the level I was being synced to was supposed to have 30 only (because I was lacking the trait for 3 total)


It looks like you may be here right now, so I'll post this part of the explaining and continue editing further :)

**Comment by vitharr137** [comment]
In case it doesn't ping properly, the more complete description for your questions has been edited in

**Comment by kaedys** [comment]
Ok, I'm going to need to look at this in more depth tomorrow when my brain is against functioning properly, and see if I can figured out how to adapt `CalcBestAction` for the changes.

**Comment by kaedys** [comment]
Conversation on this will continue in #305
