### ISSUE TITLE
Request: DRG - Nastrond -> Geirskogul

### ISSUE THREAD

**Issue by EBlaster** [MKhayle/XIVComboExpanded#221]
Spamming Nastrond before blood ends won't let Geirskogul get into the casting queue, making it inevitably shift over time.

Replacing Nastrond with Geirskogul when [blood time < Nastrond cooldown] will do the job.

**Comment by MKhayle** [comment]
With Dawntrail's DRG mini-rework, this doesn't seem to be an issue anymore
DRG stuff will be updated in the next release of the plugin as a consequence.
