### ISSUE TITLE
[Request] Under 6 seconds remaining change Storm's Path into Storm's Eye.

### ISSUE THREAD

**Issue by ZingKaruKek** [MKhayle/XIVComboExpanded#242]
Can the same feature that MNK has in the form of "True Strike / Twin Snakes Feature - # 99: Replace True Strike with Twin Snakes if Twin Snakes has less than 6s remaining or isn't applied yet." be applied to Warrior as well?

**Comment by ZingKaruKek** [comment]
Thank you for the response, looking forward to the update!

**Comment by MKhayle** [comment]
I just realized that it was already the case with the Storms Path Combo, which replaces Path by Eye if Surging Tempest has less than 20 seconds remaining. 
I don't play unga bunga often, I'll admit.
