### ISSUE TITLE
[REQUEST] RPR: Replace Soul Slice with whichever of Gibbet or Gllows is Currently Enchanted while Reaving

### ISSUE THREAD

**Issue by akkathor** [MKhayle/XIVComboExpanded#243]
Hello there, Is there a way you can add the following option for:

151: Replace Soul Slice with Gibbet while Reaving or Enshrouded
150: Replace Soul Slice with Gllows while Reaving or Enshrouded
NEW:  Replace Soul Slice with whichever of Gibbet or Gllows is Currently Enchanted while Reaving

And add the same for Soul Scythe?
NEW:  Replace Soul Scythe with Guillotine while in Reaving

Thanks!

**Comment by MKhayle** [comment]
I'll have to look into RPR because I never played it so far. I'll address this probably when I'll have time!

**Comment by akkathor** [comment]
Sounds good, thanks for this!
If you need to test anything, feel free to reach me, I would be happy to test it! :)

**Comment by MKhayle** [comment]
will probably be added after the DT initial update along with 91-100 updates

**Comment by MKhayle** [comment]
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!
