### ISSUE TITLE
Last Dance feature is broken

### ISSUE THREAD

**Issue by Zeffuro** [MKhayle/XIVComboExpanded#246]
When enabling Last Dance feature it always changes Standard Step even when Standard Step still needs to be used.

(Doesn't matter if you're in combat or not)

![ffxiv_dx11_2024-07-02_01-54-03](https://github.com/MKhayle/XIVComboExpanded/assets/4972345/cd9c0c15-3764-4785-b646-18a3e642d6a3)

**Comment by MKhayle** [comment]
Oh, yeah, my bad there. I forgot to check the status. Couldn't test since I'm still lvl 90.
Pushing a fix

**Comment by MKhayle** [comment]
it should be fixed, tell me if it is

**Comment by Zeffuro** [comment]
Yep that fixed it, thank you :)
