### ISSUE TITLE
PLD finisher Blade of Honer

### ISSUE THREAD

**Issue by ddvamai** [MKhayle/XIVComboExpanded#247]
Any way to keep the combo going from blade of valor back to "emperator" (upgrade requisiet) which is made "blade of honor" ready? Blade of honor is a ogcd finisher? If not i just have to keep a space for emperator to be able to mash it once a minute. Not a huge deal but seems like it would make sense if can be done! Thank for everyrhing!

**Comment by MKhayle** [comment]
I'm not 100% sure it'll work but I pushed a tentative fix in 1.5.0.2 https://github.com/MKhayle/XIVComboExpanded/commit/1c5ac6a6cdff3b58b60815b04c206d0ade7d2b62

Please tell me if that works out

**Comment by ddvamai** [comment]
> I'm not 100% sure it'll work but I pushed a tentative fix in 1.5.0.2 [1c5ac6a](https://github.com/MKhayle/XIVComboExpanded/commit/1c5ac6a6cdff3b58b60815b04c206d0ade7d2b62)
> 
> Please tell me if that works out
I just updated and the sequence stops with the confiteor ready button in the not ready position since it was already used and  then there is no way to keep rquiescat on another key to use the finisher blade of honor.

**Comment by MKhayle** [comment]
1.5.0.4 https://github.com/MKhayle/XIVComboExpanded/commit/87e801650e54dcf6341d8132855002a1a2a830f7 should fix it for real. 
I thought Blade of Honor was a continuation of the Blade combo (tied to Confiteor), but it's actually tied to Imperator.
Apologies!

**Comment by ddvamai** [comment]
> 1.5.0.4 [87e8016](https://github.com/MKhayle/XIVComboExpanded/commit/87e801650e54dcf6341d8132855002a1a2a830f7) should fix it for real. I thought Blade of Honor was a continuation of the Blade combo (tied to Confiteor), but it's actually tied to Imperator. Apologies!

yeah no worries! it comes from a continuation from impertator as a ogcd now

**Comment by ddvamai** [comment]
works perfect as of patch 1.5.0.4
