### ISSUE TITLE
DRG Lance Barrage and Spiral Blow not working

### ISSUE THREAD

**Issue by delphionic** [MKhayle/XIVComboExpanded#248]
The combos currently try to use Disembowel and Vorpal Thrust above level 96.

**Comment by MKhayle** [comment]
I just pushed a tentative fix in 1.5.0.3 https://github.com/MKhayle/XIVComboExpanded/commit/aa5eb0a7758894b74e4dcc8ab3fbec9f00077e54

Please update and tell me whether it fixed it or not! (my DRG is lvl 80)

**Comment by delphionic** [comment]
They now appear in the combo, but the combo drops and doesn't continue after using them.

**Comment by MKhayle** [comment]
Oh. I know why, and that's because I lack braincells.

**Comment by MKhayle** [comment]
https://github.com/MKhayle/XIVComboExpanded/commit/669867c43818ff51ecb42dff554dc2de3554c42f 1.5.0.5 should fix this.

**Comment by delphionic** [comment]
Is there any chance the version number didn't get bumped? No sign of the update yet lol

**Comment by MKhayle** [comment]
You're right, I forgot (again). It's live now!

**Comment by delphionic** [comment]
Combo is still being dropped with the update

**Comment by MKhayle** [comment]
Can you describe exactly what's happening or share a short clip?

**Comment by delphionic** [comment]
https://github.com/MKhayle/XIVComboExpanded/assets/35041046/7b555346-e4ec-4adc-922b-e971e871d7ba

**Comment by MKhayle** [comment]
Okay I get what's going on there.
I had the incorrect action data values. Pushing a final fix and I hope it'll work out this time so I can continue MSQ past lvl 90 ;_;
https://github.com/MKhayle/XIVComboExpanded/commit/5e626fe209c97725d3ef98349223caa3a54dbd8b 1.5.0.7 should fix it (and I did bump the version this time)

**Comment by MKhayle** [comment]
(please tell me if it's fixed)

**Comment by delphionic** [comment]
https://github.com/MKhayle/XIVComboExpanded/assets/35041046/90528c44-95ae-4860-be30-63bc09a1b6ef

It's now not progressing to Wheeling Thrust/Fang and Claw and then Drakesbane :v

But also, please take your time and enjoy MSQ!!!

**Comment by MKhayle** [comment]
alright, I forgot to add compatibility for level 86 skills because
I'm a lvl 80 DRG and didn't have them unlocked when I initially tested. 

https://github.com/MKhayle/XIVComboExpanded/commit/d2d689eb7c94eb1f61165a60d6e0970fbb95bd24 1.5.0.8 should *finally* get it done correctly

**Comment by delphionic** [comment]
https://github.com/MKhayle/XIVComboExpanded/assets/35041046/8f66efce-e5a9-4851-ba15-463ca33900df

The Heavens' Thrust combo is working, but the Chaotic Spring one isn't, I'm so sorry 😭

**Comment by MKhayle** [comment]
ok, that was a quick fix at least
https://github.com/MKhayle/XIVComboExpanded/commit/3c4e0429e2efa5ef677188040767a4d754a588c3 1.5.0.9 should resolve this! I mixed a `II` condition with an `&&` for chaotic, my bad there!

**Comment by delphionic** [comment]
It's working! Thank you so much!
