### ISSUE TITLE
[MCH] #82 Hypercharge Feature: Blazing Shot not working. 

### ISSUE THREAD

**Issue by Lawlsworth** [MKhayle/XIVComboExpanded#249]
Requesting an update to Hypercharge so it works when you drag the new action Blazing Shot to the hotbar as well. Right now, it's getting grandfathered in with Heat Blast, but trying to do the same with Blazing Shot doesn't work.

**Comment by MKhayle** [comment]
I forgot about this, thanks! 
https://github.com/MKhayle/XIVComboExpanded/commit/35978f7e5bd0af4adadda328089bad97515059e5 1.5.0.6 should fix it.

**Comment by Lawlsworth** [comment]
Sweet, thank you.
