### ISSUE TITLE
[Request] SCH - Seraphism to Emergency Tactics

### ISSUE THREAD

**Issue by Jaesaces** [MKhayle/XIVComboExpanded#251]
Suggestion to turn Seraphism to Emergency Tactics while under the effects of Seraphism, since Seraphism resets and drastically shortens ETactic's cooldown.

**Comment by MKhayle** [comment]
let me read what seraphism is and I'll come back to you

**Comment by MKhayle** [comment]
okay it makes sense to me but it'll be kinda hard to work blind on this
please remind me by the end of july if I still haven't done it

**Comment by MKhayle** [comment]
okay it didn't take until the end of july but I'm definitely sorry it took so long! 

I haven't tested it myself, so I hope you can give me your feedback, but it should be working with 1.5.0.22 https://github.com/MKhayle/XIVComboExpanded/commit/f3ae469a6d7d0a35691329eca9e6c289e2acebbf

**Comment by Jaesaces** [comment]
Sorry for the delay, but I have tried it ingame and appears to work! ♥
