### ISSUE TITLE
[Request] Samurai - Hakaze is not replaced by Gyofu on level 92+

### ISSUE THREAD

**Issue by iF0xer** [MKhayle/XIVComboExpanded#252]
Upon reaching level 92+ the starter combo spell "Hakaze" is changed to "Gyofu". This makes unable to execute "Gekko", "Kasha" and "Yukikaze" combos

**Comment by MKhayle** [comment]
I didn't expect that one coming.
https://github.com/MKhayle/XIVComboExpanded/commit/914803c6be99c50aa7f59e8acdf78e3dcf69a6d2 1.5.0.10 should fix this.

**Comment by iF0xer** [comment]
Now it replaces, but does not "progress" the combo on the icon, it's stuck on "Gyofu". 
Should be 
"Gyofu"> "Yukikaze" 
"Gyofu"> "Jinpu"> "Gekko"
"Gyofu"> "Shifu"> "Kasha"

**Comment by MKhayle** [comment]
I literally pushed an update for this 5mins ago, https://github.com/MKhayle/XIVComboExpanded/commit/d3c3e94b24042551b6e5bbfacb446de1938c3f57 version 1.5.0.11 should fix it

**Comment by iF0xer** [comment]
Says "update not found" and i'm stuck on 1.5.0.10, maybe need to wait <3

**Comment by MKhayle** [comment]
The repo may take 1-2min to regenerate, and you can also close/reopen the plugin installer to refetch data from it

**Comment by iF0xer** [comment]
Works now
