### ISSUE TITLE
[Request] Viper suggestions

### ISSUE THREAD

**Issue by masanbol** [MKhayle/XIVComboExpanded#253]
I generally agree that Viper doesn't need as much attention as other classes due to the combo-heavy nature of the job, but there's still a couple things I'd consider helpful around Twinfang/Twinblood:

- Twinfang/Twinblood actions replacing Swiftskin's/Hunter's Coil and Swiftskin's/Hunter's Den when followup actions are available (or replace Dreadwinder/Pit of Dread if that's easier)
- Twinfang/Twinblood actions replacing Uncoiled Fury when its followup actions are available
- Serpent's Tail replacing Steel Fang/Steel Maw, and/or Dread Fang/Dread Maw when available at the end of a normal combo
- Reawaken combo chains

Thanks! Happy to help test if you think this is worth pursuing.

**Comment by MKhayle** [comment]
I will get to there at some point, yes. Thanks for the proposal, I'll compile them along with what I already were given earlier in previous issues and sort out how I want things to work.

**Comment by masanbol** [comment]
> I will get to there at some point, yes. Thanks for the proposal, I'll compile them along with what I already were given earlier in previous issues and sort out how I want things to work.

Thank you!

**Comment by MKhayle** [comment]
work has been started in PRs #278 & #279 so there is progress (but not from me)
