### ISSUE TITLE
[DRK] Blood Weapon feature doesn't work with Delirium (Blood Weapon Mastery)

### ISSUE THREAD

**Issue by ganderhero** [MKhayle/XIVComboExpanded#255]
![Screenshot_27](https://github.com/MKhayle/XIVComboExpanded/assets/119761174/06173653-ba19-4921-9946-d1077cd46a21)
Title, after level 56 the feature doesn't work at all since you can't cast Blood Weapon and the feature replaces Quietus and Bloodspiller with Blood Weapon, not Delirium

**Comment by MKhayle** [comment]
Oh, guess I forgot to remove one Blood Weapon.
https://github.com/MKhayle/XIVComboExpanded/commit/914803c6be99c50aa7f59e8acdf78e3dcf69a6d2 1.5.0.10 should fix this.
