### ISSUE TITLE
[PCT] Hammer Motif does not replace itself with Steel Muse to continue the combo

### ISSUE THREAD

**Issue by ladyredxiv** [MKhayle/XIVComboExpanded#262]
As the title suggests. Activating Hammer Motif does not change the button into Steel Muse (and so on with Hammer Stamp) to activate the combo. I'm not sure if this was intended or not considering that pressing Steel Muse will THEN change Hammer Motif into the combo button.

**Comment by MKhayle** [comment]
Yes, that's because PCT gauge functions aren't available yet and that means I don't have a simple way to check whether the motif is active or not, so no Motif can't turn into their Muse for now. It'll be coming!

**Comment by Grammernatzi** [comment]
You can actually check whether they are active without the gauge by just checking what the original hook's actionID is. The actions change based on if motif is active or not.

**Comment by MKhayle** [comment]
Oh, that's smart! thanks for the tip

**Comment by MKhayle** [comment]
1.5.0.30 added full PCT support! 
https://github.com/MKhayle/XIVComboExpanded/commit/4d0bf20030c55cfa2bfe08c8d544a5c3267ba4fd
Have fun with it :)
