### ISSUE TITLE
[Request] SMN: Summon Solar Bahamut to Lux Solaris

### ISSUE THREAD

**Issue by Lapidearum** [MKhayle/XIVComboExpanded#263]
Requesting an option to replace Summon Bahamut with Lux Solaris while Solar Bahamut is summoned, similar to the existing Demi Enkindle feature. I like having Enkindle on a separate bind, but Lux Solaris is only usable with that particular summon yet demands its own hotbar slot.

**Comment by MKhayle** [comment]
Yeah, that one is probably going to be gauge-reliant and the client structures haven't updated gauges yet to my knowledge. 
I'd love to do this, but for now I can't do it right now, sorry! I may try to find a way around, but it's hard testing blind without being lvl 100 myself.

**Comment by MKhayle** [comment]
I'll check when I have time, there's still a chance it isn't gauge-reliant but status-reliant (do you get something like "lux solaris ready" when you summon it?)

**Comment by Lapidearum** [comment]
There is an associated status effect, Refulgent Lux!

**Comment by MKhayle** [comment]
I'll get this done soon then thanks!

**Comment by MKhayle** [comment]
https://github.com/MKhayle/XIVComboExpanded/commit/0ca9eb539793277064f9a99c7a8530443a42c46c 1.5.0.15 added it, please confirm if it's working!

**Comment by Petra105** [comment]
Can we get an option to add it to the shield?

**Comment by MKhayle** [comment]
If the current option is working on Summon Bahamut (I can't check myself), sure, I can add that tomorrow.

**Comment by MKhayle** [comment]
> Can we get an option to add it to the shield?

I added Lux Solaris Radiant Carbuncle Feature as an option for the existing Radiant Carbuncle Feature in 1.5.0.16

**Comment by Petra105** [comment]
> > Can we get an option to add it to the shield?
> 
> I added Lux Solaris Radiant Carbuncle Feature as an option for the existing Radiant Carbuncle Feature in 1.5.0.16

I think something went wrong.
https://i.gyazo.com/aedba175c9c1366f142e306b9687ad88.png

**Comment by MKhayle** [comment]
oh lmao wtf
I'm looking into it and I know what I did wrong, my bad!

**Comment by MKhayle** [comment]
Should be fixed in 1.5.0.20 https://github.com/MKhayle/XIVComboExpanded/commit/bd8c4f4e2a9adc00deaac2da4f771607a3500eb1

**Comment by MKhayle** [comment]
confirmed fixed after finally getting SCH to lvl 100
