### ISSUE TITLE
[GNB] Fated circle continuation with Demon Slaughter combo > Fated Circle Feature enabled

### ISSUE THREAD

**Issue by GSchmitt709** [MKhayle/XIVComboExpanded#265]
Can you make it so continuation replaces the Demon Slaughter button as well
When it gets replaced by Fated circle currently with the Fated Circle Feature, continuation only replaces the normal Fated Circle button but not the Demon Slaughter one,
I know it works with Burst Strike on Solid Barrel, probably same thing?

Like this i would assume :

internal class GunbreakerDemonSlaughter : CustomCombo
{
    protected internal override CustomComboPreset Preset { get; } = CustomComboPreset.GunbreakerDemonSlaughterCombo;

    protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
    {
        if (actionID == GNB.DemonSlaughter)
        {
            if (comboTime > 0 && lastComboMove == GNB.DemonSlice && level >= GNB.Levels.DemonSlaughter)
            {
                if (IsEnabled(CustomComboPreset.GunbreakerFatedCircleFeature))
                {
                    var gauge = GetJobGauge<GNBGauge>();
                    var maxAmmo = level >= GNB.Levels.CartridgeCharge2 ? 3 : 2;

					if (IsEnabled(CustomComboPreset.GunbreakerFatedCircleCont))
                        {
                            if (level >= GNB.Levels.EnhancedContinuation && HasEffect(GNB.Buffs.ReadyToFated))
                                return GNB.FatedBrand;
                        }

                    if (level >= GNB.Levels.FatedCircle && gauge.Ammo == maxAmmo)
                        return GNB.FatedCircle;
                }

                return GNB.DemonSlaughter;
            }

            return GNB.DemonSlice;
        }

        return actionID;
    }
}

**Comment by MKhayle** [comment]
oh that's a totally fair request 
let me process it when I have some time

**Comment by MKhayle** [comment]
1.5.0.16 should fix this, please let me know since I'm still lvl 90!

**Comment by GSchmitt709** [comment]
Works perfectly, thank you
