### ISSUE TITLE
Was the DT update pushed out for this?

### ISSUE THREAD

**Issue by Krojack** [MKhayle/XIVComboExpanded#266]
Dalmund went live for all today and this plugin is still disabled and says outdated yet I don't have an option to update it.

![image](https://github.com/MKhayle/XIVComboExpanded/assets/908461/fc9e88c3-e1d5-4a71-94a7-f6baa17c7ab1)

**Comment by masanbol** [comment]
This is not the main XIVCombo, it is a fork called XIVComboExpanded. The screenshot you posted is for the main XIVCombo. This fork is only available as a third party plugin and is not in the default Dalamud repository.

**Comment by MKhayle** [comment]
This Github repo is about that one specific plugin 
![image](https://github.com/MKhayle/XIVComboExpanded/assets/4359469/9ed38621-ec93-43b9-ac46-6ef7607d3748)

If you don't have the appropriate repository enabled, see [this page] (https://github.com/MKhayle/XIVComboExpanded/blob/master/README.md#installation) to learn how to do so
