### ISSUE TITLE
[REQUEST] Keeping original ability icons and cooldown info in hotbar

### ISSUE THREAD

**Issue by mil4tw** [MKhayle/XIVComboExpanded#268]
Hi, is there a way to prevent combo from changing the icons and info on at least one of my hotbars?
e.g.: MCH Drill / Air Anchor / Chainsaw and RPR Gluttony / Blood Stalk 

What I want to do is have a hotbar simply for tracking each of their cooldowns separately, but with combo enabled what I end up with now is several icons displaying the same ability if they are part of a combo

iamge example in case i didnt explain it too well: https://imgur.com/a/1srxbJ7

**Comment by MKhayle** [comment]
In the current state of the code, this isn't possible. I may try something later on, but for now, this isn't planned at all, sorry. 
However, I may have an alternative which could be helpful to help for this.

**Comment by MKhayle** [comment]
I'm keeping this issue open to share the alternative once it's available (and if it does work)

**Comment by MKhayle** [comment]
I didn't think about it but you may probably use JobBars Cooldowns feature to add a custom cooldown tracker for Drill & RPR stuff. 
Job Bars is a main repo plugin, and I don't know if it handles charges skills, but it's worth trying it out! 

![image](https://github.com/MKhayle/XIVComboExpanded/assets/4359469/43bd17e7-ca6c-4ae7-ac07-32f3f93b2f56)
![image](https://github.com/MKhayle/XIVComboExpanded/assets/4359469/b0e10ec1-1f8d-499c-b1d3-d3c9c0832a9a)
("Foreuse" is french for "Drill")

**Comment by MKhayle** [comment]
I won't fix that on my end, but I hope it may help you for CD tracking!
