### ISSUE TITLE
[Requests] {PCT} Starry Muse into Star Prism into Rainbow Drip and Motifs into Muses

### ISSUE THREAD

**Issue by Polarthief** [MKhayle/XIVComboExpanded#270]
I know in another request, someone mentioned Hammer and Motifs, and I saw it was mentioned regarding not having an easy way to detect if Motifs are up or not, so the latter half of this request is just a reminder of "hey, could this be a thing when that gets discovered?", basically Creature Motif => Living Muse, Weapon Motif => Steel Muse => Hammer Combo, and Landscape Motif => Scenic Muse.

The former half is just a request to let Scenic Muse/Starry Sky Muse become Star Prism while Star Struck is active, and further turns into Rainbow Drip when Rainbow Bright is active.

**Comment by MKhayle** [comment]
I planned to add more combos for PCT yes, including those, but I wanted to reach lvl 100 to make them myself first 
I'm sorry I'm only 94 for now, please bear with me trying to catch up on MSQ!

**Comment by MKhayle** [comment]
1.5.0.30 added full PCT support! 
https://github.com/MKhayle/XIVComboExpanded/commit/4d0bf20030c55cfa2bfe08c8d544a5c3267ba4fd
Have fun with it :)
