### ISSUE TITLE
CooldownData incorrect number of charges for MCH.Drill

### ISSUE THREAD

**Issue by diwo** [MKhayle/XIVComboExpanded#272]
`GetCooldown(MCH.Drill).RemainingCharges` returns 0 when only one of two charges have been used at level 98.

<img width="841" alt="drill_charges" src="https://github.com/MKhayle/XIVComboExpanded/assets/5284055/f3589432-9a78-4441-8b9a-ef677d8dd7ff">

**Comment by diwo** [comment]
Looks like CustomComboCache just needs to be updated to max level 100
```
var max = FFXIVClientStructs.FFXIV.Client.Game.ActionManager.GetMaxCharges(actionID, 90);
```
https://github.com/MKhayle/XIVComboExpanded/blob/3d24114/XIVComboExpanded/CustomComboCache.cs#L128

**Comment by MKhayle** [comment]
I definitely overlooked that one for the DT release, sorry! 
I think MCH is the only job who got a charges increase though?

**Comment by MKhayle** [comment]
Did it break any combo prior to this, or enable weird behaviours?

**Comment by diwo** [comment]
Drill is the only broken skill I've noticed so far. Other charges skills like Double Check and Reassemble were working correctly.

**Comment by MKhayle** [comment]
that's reassuring because I went full blind on those and double check/checkmate were scaring me A LOT lmao

**Comment by MKhayle** [comment]
I'm closing this issue for now since the initial issue is solved, if I don't think about it by the end of the month, please re-open a new issue about the potential changes to Drill combo (if any, actually, I haven't checked what it actually changes for XIVCombo)
