### ISSUE TITLE
[Bug] Dragoon's Drakesbane skill

### ISSUE THREAD

**Issue by Nillinn** [MKhayle/XIVComboExpanded#274]
Expected behavior:  The skills Fang and Claw or Wheeling Trust will turn into Drakesbane in the end of a combo.
Bug: Heaven's Trust and Chaotic Spring are also turning into Drakesbane.
This is probably happening to their low level counterparts as well (Full Trust and Chaos Trust).

Only happens with this plugin enabled. Even when every Dragoon setting is disabled in the plugin.

**Comment by MKhayle** [comment]
Oh, yeah, absolutely my bad there. I didn't set the condition in a combo context and therefore it was permanently active.
Should be fixed in 1.5.0.20 https://github.com/MKhayle/XIVComboExpanded/commit/bd8c4f4e2a9adc00deaac2da4f771607a3500eb1

**Comment by MKhayle** [comment]
confirmed fix after testing myself o7
