### ISSUE TITLE
[Bug] Fire 2 Feature - High Fire 2 is always changing to Flare when in Astral Fire

### ISSUE THREAD

**Issue by bfabe8** [MKhayle/XIVComboExpanded#280]
With Fire 2 Feature enabled, High Fire 2 is always changing to Flare in Astral Fire, instead of just in the conditions it's supposed to.

**Comment by kaedys** [comment]
That was recently changed to do that, and is intentional.  High Fire 2 had its potency gutted in DT, and Enhanced Flare is no longer a thing, so the optimal AoE rotation is now High Fire II (enter fire phase) -> Flare -> Flare -> (Flare Star) -> High Blizzard II (enter ice phase) -> Freeze -> Repeat.  High Fire II is now only good for entering fire phase, it's quite bad as an AoE spell.

**Comment by kaedys** [comment]
The level 100 AoE rotation as posted by The Balance Discord:

<img width="205" alt="20240708-014527-17e765" src="https://github.com/MKhayle/XIVComboExpanded/assets/9020449/cbdd75df-a322-439b-9fff-612cbf94d252">

**Comment by kaedys** [comment]
Looking at it in-game, though, the description of that combo probably does need to change, however.

**Comment by MKhayle** [comment]
I'll update the description before next version!

**Comment by bfabe8** [comment]
Sounds good! I wasn't aware of that 100 change, must have overlooked it. It'd be nice to have this back for <100, but understandable if you don't want to do that. Thanks!

**Comment by kaedys** [comment]
Ya, that's true, under level 100, without Flare start pushing the potency, it's worth casting 2 more High Fire IIs.  I could see an argument for integrating the lower level versions of the AoE combo in.

**Comment by MKhayle** [comment]
I will probably add a feature to disable it under lvl 100 then

**Comment by kaedys** [comment]
I don't think we want to outright disable it under 100, just modify it.  Looking at the rotations, the logic appears to be to cast Flare if and only if any of the following are true (and you're in Astral Fire):

- Level 100
- Level >= 58 and Umbral Hearts <= 1
- Level >= 50 and Mana < 3800 (ie. `BLM.MpCosts.Fire2 + BLM.MpCosts.Flare`)

And in all other cases, cast Fire II.  The latter two should be able to be combined into `if Level >= 50 && (UmbralHearts == 1 || Mana <= 3800)`

**Comment by kaedys** [comment]
Should be able to replace the current conditional that uses Flare any time you're in Astral Fire (line 309) with the following, just need to add `FlareStar` to the level and spell sections:

```
            if (level >= BLM.Levels.Flare && gauge.InAstralFire)
            {
                // Level 100 uses a simplified rotation that just uses Flare twice and then Flare Star.
                if (level >= BLM.Levels.FlareStar)
                {   
                    // FIXME: Uncomment once the Astral Soul gauge is implemented
                    // if (gauge.AstralSoulStacks >= 6)
                    //     return BLM.FlareStar

                    return BLM.Flare
                }

                // At level 50, Fire II is used until under 3800 mana (the combined cost of Fire II and Flare), 
                // and then Flare is cast once.
                // At level 58, Fire II is used until 1 Umbral Heart is remaining, and then Flare is cast twice.
                if (LocalPlayer?.CurrentMp < BLM.MpCosts.Fire2 + BLM.MpCosts.Flare || gauge.UmbralHearts == 1)
                    return BLM.Flare;
            }
```

**Comment by MKhayle** [comment]
confirmed working (at least under level 100) for me, ty!
getting that in the next release

**Comment by MKhayle** [comment]
https://github.com/MKhayle/XIVComboExpanded/commit/ddea44c198423194f598ee31a21792a4e4ad8ece there, closing this issue, thanks for the report & help!
