### ISSUE TITLE
[Bug] Summoner Gems Enkiindle Feature and Paladin Fight or Flight Goring Blade Feature with Requiescat do not work

### ISSUE THREAD

**Issue by HPDeskJet2540** [MKhayle/XIVComboExpanded#285]
Summoner Gems Enkiindle Feature during Phoenix, and Paladin Fight or Flight Goring Blade Feature with Requiescat Flight or Fiight feature do not work, not asking you to fix them right now, just thought you would like to know

**Comment by MKhayle** [comment]
I knew something was up with Summoner's Gauge and thought I had fixed everything but I guess it wasn't enough. And for PLD, I just didn't notice, so thank you !

Also thanks @kaedys for the PR, will check it out when I won't be the exhausted half-zombie I currently am

**Comment by MKhayle** [comment]
Should be fixed as per 1.5.0.25 https://github.com/MKhayle/XIVComboExpanded/commit/ef286e9429caa88574c6e8f74a9cca150c213bee
