### ISSUE TITLE
[Bug] DRK and Enhanced Delirium

### ISSUE THREAD

**Issue by delphionic** [MKhayle/XIVComboExpanded#287]
At level 96, DRK unlocks the trait Enhanced Delirium which turns Bloodspiller into a new 3 part combo (Scarlet Delirium > Comeuppance > Torcleaver) and turns Quietus into Impalement.

Currently, this isn't working with the Delirium Feature, it just keeps up the Souleater/Stalwart Soul combos instead.

**Comment by MKhayle** [comment]
I thought I had handled that correctly, but I'll check it out later today, thanks for the report!

**Comment by MKhayle** [comment]
Okay, I think I found the issue. 
The lvl 96 trait replaces the Delirium buff by another one, and I checked only the previous one because the new one didn't exist.
Pushing an update, please keep me updated and tell me if it works out.

**Comment by MKhayle** [comment]
(if it doesn't work please tell me)

**Comment by delphionic** [comment]
Is working great, thank you again!

**Comment by MKhayle** [comment]
perfect!
