### ISSUE TITLE
Failed to Load Plugin

### ISSUE THREAD

**Issue by delphionic** [MKhayle/XIVComboExpanded#288]
It's me again sorry!

Since the very recent update, the plugin refuses to load. Not sure if just a me issue or bigger issue!

![image](https://github.com/MKhayle/XIVComboExpanded/assets/35041046/813f91c2-232d-4272-a081-154532fec62f)

**Comment by MKhayle** [comment]
Is that 1.5.0.27? 
try restarting anyway, should have been fixed, I messed up with 1.5.0.26

**Comment by YarrikVII** [comment]
![ffxiv_dx11_ar0QOiDVMJ](https://github.com/MKhayle/XIVComboExpanded/assets/58294584/ba33405f-6896-4103-951a-19c9d95d5f22)

**Comment by MKhayle** [comment]
Yeah, I'm looking into it, I think I know why

**Comment by MKhayle** [comment]
Okay, 1.5.0.28 should have fixed the entries I forgot to adjust

**Comment by wynnforthework** [comment]
![image](https://github.com/user-attachments/assets/f44c11a4-30a9-4186-9438-e137e5a71b3a)
While in v2.0.1.1 failed to load plugin again.

**Comment by MKhayle** [comment]
Are you playing on the Chinese version of the game?
