### ISSUE TITLE
Plugin Failed To Load

### ISSUE THREAD

**Issue by Mightbejazzy** [MKhayle/XIVComboExpanded#289]
Had an update about 10 minutes ago, after the update the plugin no longer loads.

**Comment by MKhayle** [comment]
answered in #288 : 

> Is that 1.5.0.27? 
> try restarting anyway, should have been fixed, I messed up with 1.5.0.26

**Comment by YarrikVII** [comment]
Can verify it is 1.5.0.27

**Comment by MKhayle** [comment]
should be fixed in 1.5.0.28
