### ISSUE TITLE
[Bug] Pictomancer abilities at low level transform into the next action even when below the level requirement 

### ISSUE THREAD

**Issue by AltinaXIV** [MKhayle/XIVComboExpanded#293]
For example, if you are in content where you are level 37, the aoe combo will still turn into "Water in Blue II" even though it is a level 45 ability.

**Comment by MKhayle** [comment]
I'll add a level check, thanks for the report! It's a bit hard to track leveling for a job starting at 80 and with baked-in combos.

**Comment by kaedys** [comment]
@MKhayle rather than brute forcing it, why not just return `OriginalHook()` of the base spell?  No need to check buffs and return the specific spell that way, and it handles the level sync issue automagically.

I actually did something similar with the Paladin Confiteor combo locally, since it automatically changes in the base game already as well.

**Comment by MKhayle** [comment]
If I remember correctly, I didn't want to rely on OriginalHook() for that one because of its baked-in nature and I was being very cautious when DT released. I'll probably do that yes, but I need to stop waking up and play gachas in-between 2 sessions of sleeping 😭

**Comment by kaedys** [comment]
🤣 I feel that.  My circadian rhythm appears to be run by a meth-addled squirrel.

**Comment by MKhayle** [comment]
Honestly this is weird because I'd thought every steps of the baked-in combos would be at the same level, but it's obviously not the case

**Comment by kaedys** [comment]
Ya, it's only only the Subtractive combos that work that way.  Quite annoying.

**Comment by MKhayle** [comment]
as per https://github.com/MKhayle/XIVComboExpanded/commit/8885bd6885ba0a15cb5e2439936d2cd5d1e8967c
1.5.0.32 incoming

**Comment by MKhayle** [comment]
Thanks again for reporting this!

**Comment by MKhayle** [comment]
after testing myself : it fine
