### ISSUE TITLE
Lost functionality with recent picto update (Striking muse to hammer combo)

### ISSUE THREAD

**Issue by Mageee** [MKhayle/XIVComboExpanded#294]
i much preferred having the hammer motif on its own, then steel muse+hammer combo on another button, so that i can track the steel muse cooldown even if i haven't painted the motif yet. this was possible before today.

would love additional options for:

1. (steel/striking muse) to (hammer combo)
2. (living/creature muse) to (mog of the ages/retribution of the madeen)

basically what we have now, but starting from the muses instead of the motifs

**Comment by MKhayle** [comment]
I will consider it, but my goal with combining Motifs + Muses on the Motifs was specifically to allow being able to track cooldowns of the Muses so I'm a bit confused as to why you can't track them anymore.
I will take a look at it after finishing sleeping and I promise I'll offer a decent alternative if needed.

**Comment by kaedys** [comment]
You can definitely track the CD as is.  I have the Motif on one button, with Motif to Muse and Muse to Hammer Time, and then I have the Muse separately on another button, which allows me to see the CD regardless of the state of the Motif button.

Note that the cooldown is on the _Muse_, not the _Motif_.

**Comment by kaedys** [comment]
Here's an example.  The top button is Weapon Motif, the bottom is Steel Muse, and this is with both `Weapon Muse/Motif Combo` and `Hammer Time` enabled:

Initial state:
<img width="42" alt="20240711-024809-f09f14" src="https://github.com/MKhayle/XIVComboExpanded/assets/9020449/5eaa1484-2f35-4120-8eff-df420201bc1c">

Paint the canvas using Weapon Motif:
<img width="38" alt="20240711-024820-d85dba" src="https://github.com/MKhayle/XIVComboExpanded/assets/9020449/dac7adff-a382-4f16-9caa-168c8ad4472b">

Use Steel Muse, activating the Hammer Time buff
<img width="42" alt="20240711-024827-c7c345" src="https://github.com/MKhayle/XIVComboExpanded/assets/9020449/4b252fe3-ed8b-4d0a-84b2-ea12b91ad1ba">

Use up the Hammer Time buff, reverting back to the initial state, except with one charge on cooldown:
<img width="39" alt="20240711-024838-9af63e" src="https://github.com/MKhayle/XIVComboExpanded/assets/9020449/40a5f373-0b19-4357-acc1-328cca2651e2">

**Comment by Mageee** [comment]
fair enough, i just didn't like the idea of needing a separate tracking-only hotbar slot that i won't even be pressing, since im used to having my keybind in a certain spot and looking at that spot for the cooldown.

for well over a week it's been possible to turn steel muse into hammer combo, without it being covered up by weapon motif, i was just hoping to get that option back.
(the living muse -> mog/madeen without motif option would just be a nice bonus, i know that wasn't a thing before)

either way, i appreciate the consideration

**Comment by MKhayle** [comment]
I'll make it an option when I'll find time

**Comment by MKhayle** [comment]
I'm going to cook something and I'm not sure I'll like it, but I'm going to try

**Comment by MKhayle** [comment]
Yeah this... this just doesn't work out. I tried 3 different iterations, but none worked as they should or ended up being obscure to maintain code-wise. I'm sorry, but I will keep things as they are right now.

My primary goal is to remove button bloating without going too far, and I do think the current options available are comfy enough. Even with 3 "useless" buttons for tracking cooldowns, this is a very minimal hotbar setup in my opinion. 
![image](https://github.com/MKhayle/XIVComboExpanded/assets/4359469/c0747916-c31f-4a70-8193-7a83b1929709)

Also, if you want an alternative for tracking cooldowns, Job Bars is a very good main repo plugin which has a very handy and customizable cooldowns feature.
