### ISSUE TITLE
[Bug] Hide to Mug/Dokumori changes Hide to unusable Mug while outside of Combat

### ISSUE THREAD

**Issue by sorayukimori** [MKhayle/XIVComboExpanded#295]
Not sure exactly why, but when  enabling the option to replace Hide with Mug/Dokumori in combat, Hide instead changes to an unusable Mug until entering combat, at which point it changes to Dokumori.
![ffxiv_dx11_OUETjcqqvq](https://github.com/MKhayle/XIVComboExpanded/assets/51539112/9391c575-f533-42d0-926f-7fbf0f59586f)

If I had to hazard a guess, it would probably be due to the return statement for returning NIN.Mug being at line 229 instead of before the closing bracket at line 227. Swapping the two should fix the bug.

**Comment by MKhayle** [comment]
I'll get a look when I'll wake up for real, thanks for the report!

**Comment by MKhayle** [comment]
Alright, I fixed that behavior and improved the feature

**Comment by MKhayle** [comment]
should be live with https://github.com/MKhayle/XIVComboExpanded/commit/e6b267ee05f92fe11f189bffc9f894f6703669b9 1.5.0.32

**Comment by MKhayle** [comment]
Once more: thank you for the bug report
