### ISSUE TITLE
[Bug] Combo options that use Suiton don't work properly

### ISSUE THREAD

**Issue by sorayukimori** [MKhayle/XIVComboExpanded#296]
Due to Dawntrail reworking Ninja, combo options that use the old Suiton buff (Ten Chi Jin to Meisui, Kassatsu to Trick Attack) no longer function as intended.
Suiton (the buff) got replaced with Shadow Walker, which is granted by both Suiton (the attack) and Huton now. Replacing the former bufff with Shadow Walker hypothetically fixes the issue - Wish I could supply a bit more info.

**Comment by MKhayle** [comment]
I missed that bit, will definitely take care of it in the day. I had planned to rework NIN a bit anyway and try to take care of the new gauge thing at the same time, but it looks my preliminary attempts to fix NIN were uhhh a failure (see #295)
Thanks a lot for the report!

**Comment by sorayukimori** [comment]
No worries! These were the only things I happened to notice were broken, so overall still a success!

**Comment by MKhayle** [comment]
should be live with https://github.com/MKhayle/XIVComboExpanded/commit/e6b267ee05f92fe11f189bffc9f894f6703669b9 1.5.0.32

**Comment by MKhayle** [comment]
Also, thank you for reporting it, I appreciate that

**Comment by sorayukimori** [comment]
Confirmed fixed, awesome job! If I notice any other bugs, I'll let you know.
