### ISSUE TITLE
[MNK] Ticking options don't seem to work??

### ISSUE THREAD

**Issue by xmachina2077** [MKhayle/XIVComboExpanded#297]
When I tick the ui boxes off the abilities dont change in game

**Comment by MKhayle** [comment]
see this comment : https://github.com/MKhayle/XIVComboExpanded/issues/292#issuecomment-2221775588

**Comment by xmachina2077** [comment]
> see this comment : [#292 (comment)](https://github.com/MKhayle/XIVComboExpanded/issues/292#issuecomment-2221775588)
> 
> > You can: either type /xlbranch and pick the stg branch, or patiently wait until Dalamud's release has caught up on staging

thank you, if i change the branch can i revert it back in case there are issues??

**Comment by MKhayle** [comment]
yes, using the exact same process! the original branch is `release`
