### ISSUE TITLE
[Bug] Paladin 'Fight or Flight Goring Blade Feature' does not work on Requiestcat button with 'Requiestcat Fight or Flight Feature' enabled

### ISSUE THREAD

**Issue by HPDeskJet2540** [MKhayle/XIVComboExpanded#298]
**Describe the bug**
Paladin 'Fight or Flight Goring Blade Feature' does not work on Requiestcat button with 'Requiestcat Fight or Flight Feature' enabled.
**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have: V1.5.0.35
2. Which job is affected: Paladin
3. What are your enabled combos for that job: 'Royal Authority Combo' 'Royal Authority Divine Might Feature' Prominence Combo' 'Prominence Divine Might Feature' 'Requiescat Fight or Flight Feature' 'Fight or Flight Goring Blade Feature' 'Confiteor Feature' 'Scornful Spirits Feature' 'Shields on your Feet Feature'
4. Which skill is placed in your hotbar: 'Royal Authority' 'Atonement' 'Holy Spirit' 'Spirit Within' 'Intervene' 'Requiescat'
5. Are you using any other XIVCombo fork? because you shouldn't: No
**Expected behavior**
The Requiestcat button will start as Fight or Flight and then change to Requiestcat (correct so far), after both are pressed, it should change to Goring Blade to my understanding, but it stay as Fight or Flight.
**Screenshots or videos**
If applicable, add screenshots/videos to help explain your problem.
[Video example](https://youtu.be/rGU1gvOACto)
**Additional context**

**Comment by MKhayle** [comment]
Okay, so having Requiescat Confiteor "fixes" this issue but should maybe have a better description. 
I'm not quite sure what I want to do there, but I'll take a look at it ; the goring blade change is a bit annoying in general

**Comment by kaedys** [comment]
Ya, the existing FoF Goring Blade one is basically obsolete.  Since FoF naturally turns into Goring Blade baseline now, it should probably just be the normal behavior, and if you enable Req + FoF, it also gains Goring Blade.  However, to also be compatible with the user's selection of whether FoF turns into Goring Blade in the game's normal Actions settings, we should probably check the OriginalHook on it first.

**Comment by MKhayle** [comment]
I would gladly let you handle PLD because there's been lot of changes on it over the 2 last years and I'm prone to mixing old things with new things
(also, since I am playing with a french client, getting used to english PLUS french names for skills or buffs is very exhausting)

**Comment by kaedys** [comment]
Haha, okie, I'll clean up the change I've been working with locally and get a PR put together for it.

**Comment by MKhayle** [comment]
(that's the reason why VPR is scaring the hell out of me)
