### ISSUE TITLE
[Request] Pictomancer Rainbow Drip combo when Rainbow Bright is active

### ISSUE THREAD

**Issue by HPDeskJet2540** [MKhayle/XIVComboExpanded#299]
**Describe the feature you'd like**
Fire in Red combo and Fire II in Red combo turn into Rainbow Drip when under the buff ‘Rainbow Bright’, can also change Fire in Red into Rainbow Drip when out of combat, since Pictomancer prepull with Rainbow Drip hard cast.

**Describe alternatives you've considered**
Holy in White turns into Rainbow Drip when under the buff ‘Rainbow Bright’, can also change Holy in White into Rainbow Drip when out of combat, since Pictomancer prepull with Rainbow Drip hard cast.

**Additional context**
Add any other context or screenshots about the feature request here. Mock-ups are fine too.

**Comment by MKhayle** [comment]
the alternative can be added as a non-secret combo though, I like this idea
I'll also consider the Rainbow Drip starter option

**Comment by HPDeskJet2540** [comment]
My apology, I did not realize the Fire in Red into Rainbow Drip is already implemented, thank you for the hard work!

**Comment by MKhayle** [comment]
![image](https://github.com/MKhayle/XIVComboExpanded/assets/4359469/7127af91-2dad-4e35-8bd1-3a8cab25d11a)
https://github.com/MKhayle/XIVComboExpanded/commit/53a5e002998a486eaf01e7b8b479ac8bc7d167e8 1.5.0.36 should cover these additions
