### ISSUE TITLE
BLM combos

### ISSUE THREAD

**Issue by El-Guapo15** [MKhayle/XIVComboExpanded#304]
**Describe the bug**
Since the latest patch the BLM combos are not working, hopefully user error.  I have check other classes such as RPR and it's working just fine.

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have: 1.5.0.42
2. Which job is affected:  Right now seems only to be BLM
3. What are your enabled combos for that job:  Fire 1/3 Feature and Blizzard 1/3 Feature just to test
4. Which skill is placed in your hotbar:  I dragged Fire 1 down, same with Blizzard 1
5. Are you using any other XIVCombo fork? because you shouldn't:  Negative

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by kaedys** [comment]
@El-Guapo15 can you expand on the issue you're having?  You indicate the combos you've got enabled, but not what behavior you're actually seeing versus what you expected.  I just confirmed locally that both the `Fire 1/3 Feature` and the `Blizzard 1/3 Feature` are working as expected on my black mage, so we'll need more details to even know what sort of bug to be looking for.

**Comment by El-Guapo15** [comment]
Hi @kaedys , happy to expand on the issues I'm having.  Earlier in the day I was able to use both features above, I dragged the Fire icon from my Actions to my hotbar and it displayed as Fire III, same for blizzard.  Once I logged on later in the afternoon the plugin updated and I notice that the icons on my hotbar displayed as just Fire and Blizzard.  I went into battle and confirmed that neither changed from Fire/Blizzard to Fire III / Blizzard III.  

The same happened with the Enochian Feature, it wouldn't change based on the action that was available, I had to put both actions back on my hotbar.  Same can be said for the Freeze/Flare Feature. 

I haven't had any issues with any class except for BLM.  I've tried restarting the game, disabling the plugin and restarting and removing the repo all together and re-adding it.

**Comment by MKhayle** [comment]
This is because you aren't using the `staging` version of Dalamud and I have introduced the Astral Soul feature using the new BLM gauge which hasn't been implemented yet in the `release` version of Dalamud. It's featured in the `staging` version, which is akin to a (public) testing version. 
It's the exact same issue that MNK players had, and the options are the same:
> You can: either type /xlbranch and pick the `stg`/`staging` branch, or patiently wait until Dalamud's `release` has caught up on staging. If you're afraid or anything, you can pick back the `release` branch the exact same way.

**Comment by El-Guapo15** [comment]
@MKhayle that worked, thank you!
