### ISSUE TITLE
[Request]Astral/Umbral draw on Play 1/2/3

### ISSUE THREAD

**Issue by Petra105** [MKhayle/XIVComboExpanded#307]
Can Astral/Umbral draw be on Play 1 when there is no card to play. or any of the plays when there are no cards to play?

**Comment by MKhayle** [comment]
I haven't been working on AST as of yet, since it's been fully reworked and I haven't familiarized myself with it.
I will take care of it soon, I just didn't have time for it as some other jobs had priority (new jobs & monk, notably) and AST also requires a gauge update which may not be available yet. But it was planned and I will address it!

**Comment by kaedys** [comment]
Looks like the AST gauge has in fact been [updated for DT](https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Game/ClientState/JobGauge/Types/ASTGauge.cs), fortunately.  Probably just 4 different combos where if DrawnCards is empty and DrawnCrownCard is None, place Draw on Play 1, Play 2, Play 3, or Minor Arcane, and the user can select any or all of those to taste.

**Comment by MKhayle** [comment]
neat! I'll try to bake something tonight

**Comment by MKhayle** [comment]
https://github.com/MKhayle/XIVComboExpanded/commit/46b5ca296919ec6b33066f072a73088ff3a8d76e done
https://github.com/MKhayle/XIVComboExpanded/commit/92feca57359c465b7dfe0861683f876d9389bf8e 1.5.1.1 is available with some first features (which may or may not be to your liking, but were what I considered the most sensible ones)

**Comment by MKhayle** [comment]
https://github.com/MKhayle/XIVComboExpanded/commit/f6012047b0167ad02a639dc5e62395a001391c18 1.5.1.2 adds some level checks features for level sync because SE does weird things with minor arcana

**Comment by MKhayle** [comment]
I just realized I literally opted for 5 combos and literally none of them cover your initial request

I feel super stupid

**Comment by MKhayle** [comment]
oh wait yes one does!!! 
I'm un-stupid
I can close this
