### ISSUE TITLE
[Bug] Action replacements do not function on Monk

### ISSUE THREAD

**Issue by starafar** [MKhayle/XIVComboExpanded#308]
**Describe the bug**
Action replacements do not seem to take effect on Monk.

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Plugin version 1.5.0.42.
2. Monk
3. Opo Feature, Raptor Feature, Coeurl Feature, Monk AoE Combo, Perfect Balance Feature
4. For testing purposes, I have Dragon Kick, Twin Snakes, Demolish, Leaping Opo, Rising Raptor, and Pouncing Coeurl all on my bar. Also present is Masterful Blitz and Perfect Balance.
5. I am not using any other fork.

**Expected behavior**
With the mentioned features enabled:

1. Leaping Opo should be replaced with Dragon Kick when at zero Opo's Fury stacks.
2. Rising Raptor should be replaced with Twin Snakes when at zero Raptor's Fury stacks.
3. Pouncing Coeurl should be replaced with Demolish when at zero Coeurl's Fury stacks.
4. Masterful Blitz should be replaced with Shadow of the Destroyer.
5. Perfect Balance should be replaced with Elixir Burst, Rising Phoenix, or Phantom Rush depending on beast chakra.

**Actual behavior**
The hotbar functions as if none of these features are enabled. No action replacements occur whatsoever. I have tested other jobs listed as updated for Dawntrail such as SAM and GNB, and action replacements occur as expected on those jobs. Monk seems, for me at least, to be broken.

**Additioal Context**
I shut down the game and deleted the plugin config from `%appdata%\XIVLauncher\pluginConfigs`, then relaunched the game and reconfigured the plugin, just to make sure it wasn't some remnant config garbage from prior versions. This did not help.

**Comment by MKhayle** [comment]
This is because you aren't using the `staging` version of Dalamud and I have introduced features using the new MNK gauge which hasn't been implemented yet in the `release` version of Dalamud. It's featured in the `staging` version, which is akin to a (public) testing version. 

Your options are the following:
> You can: either type `/xlbranch` in game and pick the `stg`/`staging` branch and restart your game, or patiently wait until Dalamud's `release` has caught up on staging. If you're afraid or anything, you can pick back the `release` branch the exact same way.

**Comment by starafar** [comment]
🤦 Sorry for wasting your time!

**Comment by MKhayle** [comment]
It's fine! I should have waited before pushing those updates, so it's my bad I guess.
