### ISSUE TITLE
API Request: Get Cast Time of Abilities

### ISSUE THREAD

**Issue by lhn1703** [MKhayle/XIVComboExpanded#313]
I want to implement a secret combo feature for black mage that changes Fire 4/Despair into other buttons if Enochian timer would run out before the cast finishes. I am not familiar with the greater Dalamud API, so am wondering if @MKhayle or anyone else knows how to get the cast time of say base Fire 4/despair, and under ley lines (of course taking into account spell speed from gear and such).

If you feel the feature does not belong in this fork then feel free to close this issue.

**Comment by MKhayle** [comment]
hahahahaha 
please see #305's ongoing discussion about the `CooldownData.cs` rework

**Comment by MKhayle** [comment]
oh, I just realized you mentioned cast time and not cooldown time

I will check it out tomorrow because it's 4am here 🛌🏻

**Comment by kaedys** [comment]
Technically, it's related, since the cooldown data has a CastTime field as well, but I'm not in the midst of modifying it.  If you get the cooldown data for the ability and check the `CastTime` field, which returns the spell speed adjusted cast time of the ability, and compare that against the remaining duration of Astral Fire, that'd work.  But note that when the debuff _expires_ versus when it stops being able to be _refreshed_ are not always the same thing.  The server seems to have some grace period around it.

**Comment by kaedys** [comment]
Ok, now that #314 is submitted, you should be able to do the following:

```
var fire4 = GetCooldown(BLM.Fire4);
var gauge = GetJobGauge<BLMGauge>();

if (astralFire is not null && gauge.ElementTimeRemaining/1000.0 > fire4.CastTime)
    return BLM.Fire4;

// Do whatever you want to do if it'll expire before the cast finishes, probably Paradox or Fire 3.
```

**Comment by lhn1703** [comment]
Nice, I'll wait for #314 to be pulled into master before making the feature.

**Comment by kaedys** [comment]
I actually didn't change the CastTime function at all, so you should be fine even with what's on master, as long as you don't try to use any of the cooldown or charge functions (as their names changed and were consolidated in 314).

**Comment by lhn1703** [comment]
> Ok, now that #314 is submitted, you should be able to do the following:
> 
> ```
> var fire4 = GetCooldown(BLM.Fire4);
> var gauge = GetJobGauge<BLMGauge>();
> 
> if (astralFire is not null && gauge.ElementTimeRemaining/1000.0 > fire4.CastTime)
>     return BLM.Fire4;
> 
> // Do whatever you want to do if it'll expire before the cast finishes, probably Paradox or Fire 3.
> ```

I am getting this error:
![image](https://github.com/user-attachments/assets/b1ddba51-edef-4294-9b95-36531f5ac653)

**Comment by kaedys** [comment]
Odd, it's definitely there.  I'll have to take a look further in the morning

```
    public unsafe float CastTime => ActionManager.GetAdjustedCastTime(ActionType.Action, this.ActionID) / 1000f;
```

**Comment by kaedys** [comment]
Ah, my mistake, apparently CastTime is _not_ in the version of the CooldownData update currently on master.  Apologies.  So you'll either have to wait for 314, or base your branch off my branch in that PR.

**Comment by MKhayle** [comment]
It's merged, have fun

**Comment by MKhayle** [comment]
does it solve your issue btw

**Comment by lhn1703** [comment]
Yea, error is fixed now with the latest master.
