### ISSUE TITLE
[Bug] BLM combos not working

### ISSUE THREAD

**Issue by SchmooplesVT** [MKhayle/XIVComboExpanded#315]
**Describe the bug**
None of the Black Mage combo abilities work as intended. 

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have: 1.5.1.2
3. Which job is affected: Only Black Mage that I have found.
4. What are your enabled combos for that job: Enochian (does not change Fire IV or Blizzard 4). Transpose into Umbral Soul(Does not change Transpose when in Umbral Ice active). (Between the) Ley Lines(Does not change Ley Lines). Fire 1/3(Does not change Fire 1 to Fire 3 with Firestarter). Blizzard 1/3, Freeze/Flare. None work as intended.
5. Which skill is placed in your hotbar: Have tried all. The combo abilities work when using other classes but nothing for Black Mage works. Dragging Fire IV and Blizzard IV onto the hotbar at the same time does not change either one when under Umbral Ice or Astral Fire.
6. Are you using any other XIVCombo fork? because you shouldn't: No, just this one. 

**Expected behavior**
 -None of the Black Mage combo abilities seem to be working. Tested combos with Bard, Warrior, and Paladin and all worked as intended but I can't get any Black Mage combo ability to work.

**Screenshots or videos**
If applicable, add screenshots/videos to help explain your problem.
 -https://media.discordapp.net/attachments/907966596763500586/1261531848681590824/image.png?ex=66934c96&is=6691fb16&hm=c212ffb202941b601200f578025695fca2650a282f184459eb5874fce03c1995&=&format=webp&quality=lossless&width=550&height=309
 -In this screenshot I am in Umbral Ice. With Enochian Feature enabled, Fire IV should be displaying as Blizzard IV(circled area) but it is still showing Fire IV.

**Additional context**
 -Tested with all other plugins disabled. Same issue.

**Comment by kaedys** [comment]
See #304.  MKhayle merged the BLM changes after the gauge was added to Dalamud master, but before it was pushed to the release branch.  I believe it is still on the staging branch.  MKhayle detailed the options in this post: https://github.com/MKhayle/XIVComboExpanded/issues/304#issuecomment-2225253421

**Comment by SchmooplesVT** [comment]
Tested and switching to staging version of Dalamud fixed the issue. Thank you!
