### ISSUE TITLE
[Bug] Any of the black mage features work.

### ISSUE THREAD

**Issue by nacruno** [MKhayle/XIVComboExpanded#316]
**Black Mage Features does not work**
A clear and concise description of what the bug is. - other then the problems i stated under any of the black mage features doesn't seem to work for me. (other jobs features work perfecty)

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have - v1.5.1.2
2. Which job is affected - Black Mage
3. What are your enabled combos for that job - Enochian Feature, Transpose into Umbral Soul, Freeze/Flare Feature,
4. Which skill is placed in your hotbar - tried placeing and removing every relevant skill
5. Are you using any other XIVCombo fork? because you shouldn't - i had the older xivcomboplugin installed since before dt but it's deleted now.

**Expected behavior**
A clear and concise description of what you expected to happen. - expecting for blizz4 and freeze to stay as is in umbral ice and change to fire4 and flare in astral fire

**Screenshots or videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by MKhayle** [comment]
This is because you aren't using the `staging` version of Dalamud and I have introduced the Astral Soul feature using the new BLM gauge which hasn't been implemented yet in the `release` version of Dalamud. It's featured in the `staging` version, which is akin to a (public) testing version. 
It's the exact same issue that MNK players had, and the options are the same:
> You can: either type `/xlbranch` in game and pick the `stg`/`staging` branch and restart your game, or patiently wait until Dalamud's `release` has caught up on staging. If you're afraid or anything, you can pick back the `release` branch the exact same way.
