### ISSUE TITLE
[Bug] AST Malefic/Gravity to Arcana does not work if Malefic to Astral/Umbral Draw isn't ticked

### ISSUE THREAD

**Issue by Propagandist1** [MKhayle/XIVComboExpanded#320]
**Describe the bug**
Upon casting Astral Draw, AST are given the Lord of Crowns card.  The combo option "Malefic/Gravity to Arcana" seems to be intended to replace Malefic/Gravity with Lord of Crowns if Lord of Crowns is drawn.  Instead, Malefic and Gravity remain as Malefic and Gravity.  However, if you also tick the "Malefic to Astral/Umbral Draw" option, Malefic is replaced with Lord of Crowns.  If you also tick the "Gravity to Astral/Umbral Draw" option, Gravity is replaced with Lord of Crowns.

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have: 1.5.1.4
2. Which job is affected: AST
3. What are your enabled combos for that job: 8, 9, 10, 11.
4. Which skill is placed in your hotbar: All of them
5. Are you using any other XIVCombo fork? because you shouldn't: No

**Expected behavior**
Malefic/Gravity change to Lord of Crowns when Astral Draw is cast.

**Comment by MKhayle** [comment]
Oh yes, I forgot to fully unlink those two options (it was designed as a standalone feature at first). Thanks for your report, I'll look at it today!

**Comment by MKhayle** [comment]
https://github.com/MKhayle/XIVComboExpanded/commit/19c8dc2d83d3234641beded45cb791db600cbdbd
fixed there, I'll push an update later today after some testing on another change
