### ISSUE TITLE
Viper: One button Reawaken into Generation and Legacy 

### ISSUE THREAD

**Issue by baelrayneVessdren** [MKhayle/XIVComboExpanded#324]
Hi. 

Is it possible to condense the Reawaken > Generations > Legacy combo into Reawaken?

Rotation is self contained so no other buttons / abilities would be affected. 

Thanks for this great mod and your continued work. 

BR

**Comment by MKhayle** [comment]
Try typing `/pcombo secrets` and check for yourself ;)

**Comment by baelrayneVessdren** [comment]
I did and it doesn't do anything :) But I do think I know what you mean. The Fanged Tails combo with the additional information about Reawakening (not hidden by Secrets). 
That argument is flawed though, imo. Unlike the basic Steel- and Dreadfangs combo, the Reawakening combo has a fixed set of skills: 
Awakening > First Generation > First Legacy > Second Generation > Second Legacy > ........ > Ouroboros. That, in my opinion, is more like a basic 1, 2, 3 combo. As it is right now, you have a higher risk of messing it up, then you would have otherwise. 
**BUT** for arguments sake, let's say it is not and keep your solution. Could you maybe make two different options out of Fanged Tails and Reawakening?

**Comment by MKhayle** [comment]
Are you up to the latest version? 1.5.1.5 should have this: 
![image](https://github.com/user-attachments/assets/c261117e-6f32-4994-9482-35f88bd9953d)

**Comment by MKhayle** [comment]
Updates are *very* frequent lately and if you still encounter issues with this, refer to #317 since gauge stuff is involved

**Comment by baelrayneVessdren** [comment]
Huh. For some reason Combo did not show as Update available, nor did it auto update. My bad. Feature is there and I am a happy little snek.

Thanks again for your hard work and this incredible mod.
