### ISSUE TITLE
[Request] AST Play 1-2-3 

### ISSUE THREAD

**Issue by bluesolei1** [MKhayle/XIVComboExpanded#325]
Might be unpopular request but still

**Describe the feature you'd like**
Since DT rework AST now have 3 play buttons, and now keybinds are in shambles. 
Would be neat to have combos as follow:

- Malefic -> Play 1
- Combustion -> Play 2
- Gravity -> Play 3

**Comment by MKhayle** [comment]
yes, probably, as an easycombo probably

**Comment by kaedys** [comment]
What's your intent with the targeting on this, @bluesolei1?  All of the Play cards are friendly targeted, but you're asking for them to be placed on hostile-targeted spells.  Are you intending for them to be self-cast?  If so, it's going to be little better than just not casting them at all.  Or are you intending to cast the hostile spells using a target-of-target redirect (via macros or a mod like Redirect), and thus the cards would be cast on the tank?  Still distinctly non-optimal for the DPS card, but workable, I guess.  Note that in most cases, you won't be casting both Gravity and Malefic during a given combat minute, so you'll still need to remember to hit the other one (ex. hitting the Gravity button during single target, even though you're not trying to AoE) to use the card.

**Comment by MKhayle** [comment]
They may be using MouseOverAction tho

**Comment by kaedys** [comment]
Ya, that would work at least for Play 2 and Play 3, though I'm still not sure of the logic of tying them to the primary ST and primary AoE fillers, since you basically never use those together.  And Play 1 should probably go on a DPS instead.  Does MouseOverAction or Reaction support fixed targeting?  They could work for Play 1, at least, if it were set to just auto-cast at a DPS by placeholder (like <d1>)

**Comment by MKhayle** [comment]
MoA/Reaction allows for targeting the target of the target, or hovering a party member (in the party list or on the field) to target them, so I guess it may work out. Some people have specific setups and with the mention of it being an non-optimal, that would be okay I think.

**Comment by bluesolei1** [comment]
Actually, thank you for mentioning ReAction stacks, fiddled with it  and it does provide ability to do what i wanted

For whoever struggles with same keybind issues, these are the ReAction settings
![image](https://github.com/user-attachments/assets/ac3ff9e5-e34f-40ba-b3d5-431b8fc3cab9)
 
Targeting enemy it casts normal damaging spell, mouseovering party frame it cast Play.

**Comment by kaedys** [comment]
Ya, that's how I handled Bard song rotations before we had a combo for it.

**Comment by bluesolei1** [comment]
Solved with ReAction stacks, thanks to @kaedys
