### ISSUE TITLE
[Bug] Royal Authority Atonement Feature Issue

### ISSUE THREAD

**Issue by Propagandist1** [MKhayle/XIVComboExpanded#327]
**Describe the bug**
I think the Royal Authority Atonement Feature may not be working correctly.  If I select option 121 (Royal Authority Combo), the Royal Authority button correctly cycles between Fast Blade, Riot Blade, and Royal Authority.  If I also select option 124 (Royal Authority Atonement Feature), then when I execute the main combo as above, Royal Authority doesn't always turn into Atonement and its follow-on combo.  It sometimes seems to prematurely revert back to Fast Blade, even if Atonement Ready is up.

I have Atonement assigned to a button right next to it, so I can see when Atonement is available.  But Royal Authority sometimes just swaps back to Fast Blade instead of changing into Atonement.  You can see it briefly change to Atonement, but a half a second later it's back to Fast Blade.

Strangely, if I execute the main combo again, it will eventually change into Atonement.  In this case, it gets into this strange loop that goes Fast Blade, Riot Blade, Atonement, Supplication, Sepulchre, Royal Authority.  Kind of like a 1, 2, A, B, C, 3 thing.  

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have: 1.5.1.5
2. Which job is affected: PLD
3. What are your enabled combos for that job: 121, 124
4. Which skill is placed in your hotbar: Royal Authority and Atonement
5. Are you using any other XIVCombo fork? because you shouldn't: No

**Expected behavior**

1, 2, 3, A, B, C all on one button
Fast Blade -> Riot Blade -> Royal Authority -> Atonement -> Supplication -> Sepulchre

**Screenshots or videos**
![test](https://github.com/user-attachments/assets/edc31694-55fb-4970-b684-3dcd5cc6fd56)

**Additional context**
If I'm misinterpreting the intent of these options, I apologize.

**Comment by MKhayle** [comment]
Yes, you should use the Atonement Follow-up feature instead, because enable a child feature also enables the parent feature. Atonement Follow-up is a stand-alone feature for your usecase.

**Comment by MKhayle** [comment]
@kaedys, this is another example of why #323 becomes more & more necessary imo

**Comment by Propagandist1** [comment]
Thank you for the quick response!  

I've disabled option 124 (Royal Authority Atonement Feature), kept option 121 enabled (Royal Authority Combo), and enabled option 127 (Atonement Follow-up).  The Royal Authority Combo reverts back to Fast Blade upon concluding the combo, while the Atonement Ready is available.  

If I disable option 121 (Royal Authority Combo) and option 124 (Royal Authority Atonement Feature), and have only option 127 enabled (Atonement Follow-up), then the Royal Authority button stays as Royal Authority until Atonement Ready is available.  

I can't seem to find a combination of these options to achieve the 6-button combo.

**Comment by MKhayle** [comment]
Oh, well, yes. This is something we're actually sorting out because of conflicting opportunities for the player base and we want to improve this "split" to avoid this kind of confusion.

**Comment by kaedys** [comment]
Ya, so, that's very intentional that it does that, because from an optimization perspective, you should delay using Atonement until it would be overwritten, because that lets you potentially delay it into Fight or Flight, and there's zero loss by delaying it until after Rio Blade.

And ya, MKayle, good example of this needing two versions, the "intuitive" but unoptimized version, and the optimized one.

**Comment by Propagandist1** [comment]
Ah, I understand.  It seems I was misinterpreting the description and the 1-button, 6-ability combo is not intended.  Thank you very much for the responses!  I will close the ticket, as it seems this is not a bug!

**Comment by Propagandist1** [comment]
Not a bug, working as intended.  Thank you!

**Comment by kaedys** [comment]
No, it _does_ do the 6-part combo, it just waits to use the 3-part Atonement feature until it would otherwise be overwritten by using Royal Authority again.  Basically, same reason that the Royal Authority combo doesn't immediately use Divine Might, it waits until just before the next Royal Authority cast instead.  Delaying them potentially lets you slide those higher-potency actions into an upcoming FoF window, and there's no loss as long as you don't let them expire or overwrite them with another Royal Authority usage.

**Comment by kaedys** [comment]
Basically, Paladin doesn't have a 6-part combo, it has two 3-part combos, the first of which unlocks the second.  Atonement does _not_ need to immediate follow after Royal Authority, it just needs to be used before you use Royal Authority _again_ (which would overwrite and thus waste the buff).

**Comment by Propagandist1** [comment]
Wow, that's more complex than I thought it would be.  Thank you for explaining that to me.  Seems you guys have thought of everything!

**Comment by kaedys** [comment]
Ya, we're currently kicking around an idea for splitting the feature options so things like that, which aren't really necessarily _intuitive_, but _are_ better from an optimization standpoint, won't be included in the default combos and instead are included in a separate "type" of combo, indicated with a special icon.
