### ISSUE TITLE
[Request] Merge "Twin Coil Feature/ Twin Coil AoE Features with VPR PVP Style Winder Combo & VPR PVP Style AoE Combo

### ISSUE THREAD

**Issue by Zynyx** [MKhayle/XIVComboExpanded#328]
As read above, the first two features make it so post using Dreadwinder your Hunters Coil & Swiftskin's Coil buttons  progress intuitively to Twinfang Bite > Twinblood Bite

The newer PVP Style features attempt to consolidate further by moving Dreadwinder > Swiftskins Coil > Hunter's Coil; however, you still need to bind separate buttons for Twinfang and Twinblood in this stances as the if you just use those in order you miss out on the 2 oGCDs. If you don't use those oGCDs before moving to the next coil, you lose them.

The same is true regarding the Pit of Dread combo with runs Pit of Dread > Swiftskin's Den > Hunters Den but then Twinfang Thresh & Twinblood Thresh need to be bound to separate keys.

Could it instead operate: Dreadwinder > Swiftskins Coil > Twinfang Bite > Twinblood Bite > Hunter's Coil > Twinfang Bite > Twinblood Bite then reset to dreadwider? 

In the case of Pit of Dread: Pit of Dread > Swiftskin's Den > Twinfang Thresh > Twinblood Thresh > Hunter's Den > Twinfang Thresh > Twinblood Thresh then reset to Pit of Dread. 

This is suggested by grace of the fact that those abilities are used in sequence always anyway and removes 2 more buttons from the UI (Also turns 4 features into 2)

**Comment by Zynyx** [comment]
Mislabeled this as a bug as I thought I misread the behavior the first time then changed the text to request- apologies.

**Comment by Zynyx** [comment]
Will this change be coming in 1.5.1.6? The ticket was closed, but there doesn't seem to be a new version yet. 

Just wanted to make sure I'm not missing it.

**Comment by kaedys** [comment]
MKhayle has been working in the background on a major refactor, so I think the new version release got delayed.  It'll be in the next point release, though.
