### ISSUE TITLE
[Request/Bug] Ninja's "Kassatsu to Trick" update for DT

### ISSUE THREAD

**Issue by Asinin3** [MKhayle/XIVComboExpanded#337]
Ninja's "Kassatsu to Trick" feature needs to be updated. It should work with Kunai's Bane instead of trick when level 92 or higher. It should also transition when the Shadow Walker buff is applied, not suiton as the buff was changed in dawntrail

**Comment by MKhayle** [comment]
Oh, I didn't realize Trick had an evolution. That's an easy fix.

**Comment by MKhayle** [comment]
Should be fixed in https://github.com/MKhayle/XIVComboExpanded/commit/d71a1599a8132319b822f08b9feb99c8dd853965 1.5.1.7
