### ISSUE TITLE
[Bug] DNC main combo missing.

### ISSUE THREAD

**Issue by RyuuYggd** [MKhayle/XIVComboExpanded#340]
![DNC Combos Missing](https://github.com/user-attachments/assets/7557611d-82e9-455a-afed-8a6b0ad543e9)
Thanks for the work on the updates as usual!
I think a recent update made the regular combos (both Single Target and AoE) for the Dancer unavailable as an option in the game.

**Comment by MKhayle** [comment]
It exists, but for now, until the incoming rework of the plugin, you'll have to type `/pcombo secrets` to enable it
