### ISSUE TITLE
[Bug] Can't select Deprioritize Grand Impact under Verplus Feature

### ISSUE THREAD

**Issue by bfabe8** [MKhayle/XIVComboExpanded#342]
**Describe the bug**
When selecting 'Deprioritize Grand Impact' under the Verstone/Verfire Plus Feature, the checkbox is not selected

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have
2. Which job is affected
3. What are your enabled combos for that job
4. Which skill is placed in your hotbar
5. Are you using any other XIVCombo fork? because you shouldn't

**Expected behavior**
Should be selected

**Screenshots or videos**
https://github.com/user-attachments/assets/85b1e679-d014-4534-9388-48c2736d738e

**Additional context**

**Comment by MKhayle** [comment]
checking this out tomorrow!

**Comment by kaedys** [comment]
Oh, interesting.  I didn't realize the _description name_ had to be unique.  >.<

**Comment by MKhayle** [comment]
yeah, that's... yeah.

**Comment by kaedys** [comment]
I guess it's not necessarily a _bad_ restriction, identical feature names are probably inherently at risk of confusion, even with parenting, but ya, that's...oof
