### ISSUE TITLE
[Request/DRG] Combine Wyrmwind Thrust with Combos

### ISSUE THREAD

**Issue by Rubyurek** [MKhayle/XIVComboExpanded#344]
It would be great if you could combine Wyrmwind Thrust with the other three combos, so you always get to use it and don't forget it.

**Comment by kaedys** [comment]
Probably going to need to wait on #323

**Comment by kaedys** [comment]
I have a working version of this locally, for once 323 is merged in.

**Comment by MKhayle** [comment]
You can start merging in the 323 branch the!

**Comment by MKhayle** [comment]
You can start merging in the 323 branch then!
