### ISSUE TITLE
[Request] PLD Confiteor Feature into Blade of Honor

### ISSUE THREAD

**Issue by HPDeskJet2540** [MKhayle/XIVComboExpanded#345]
**Describe the feature you'd like**
Paladin's "Confiteor Feature" have lvl 100 skill Blade of Honor after using Blade of Valor

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Mock-ups are fine too.

**Comment by kaedys** [comment]
So, this is already the case, but only if you use the "Requiescat Confiteor" feature (the Prominence Confiteor or Royal Authority Confiteor features also include it).  Would using that be sufficient for your purposes?  Or do you specifically want Confiteor on a different button from Requiescat/Imperator?

**Comment by HPDeskJet2540** [comment]
Hello, yes for me personally, I like to have the Confiteor combo on the holy spirit button to aviod consuming a Requiescat stack with Holy Spirit, and using the Requiescat/Fight or Flight button to track CD and FoF duration (with jobbars plugin)

**Comment by HPDeskJet2540** [comment]
> Hello, yes for me personally, I like to have the Confiteor combo (including blade of honor) on the holy spirit button to aviod consuming a Requiescat stack with Holy Spirit, and using the Requiescat/Fight or Flight button to track CD and FoF duration (with jobbars plugin), instead of overwriting the Requiescat/Fight or Flight button with the Confiteor combo
