### ISSUE TITLE
[Bug] BLM Logic Operator Typo in Commit b681717

### ISSUE THREAD

**Issue by lhn1703** [MKhayle/XIVComboExpanded#348]
![image](https://github.com/user-attachments/assets/10776687-66f5-4e8e-80a6-1f97291215f4)

New code has the last two && and || switched, which breaks the feature.

**Comment by MKhayle** [comment]
my brain is getting overcooked but that'll be a priority fix for tomorrow

**Comment by MKhayle** [comment]
I'm really sorry I was just linting stuff and that one bit went wrong
I'm apologizing from my phone in bed
I'll fix it asap 
sorry

**Comment by lhn1703** [comment]
No worries, take as much rest as you need. This isn't as gamebreaking as crowdstrike :)

**Comment by MKhayle** [comment]
I'll fix it within the week, promise
I just wanna focus on the rework branch for now and when it's done I'll get back to main

**Comment by MKhayle** [comment]
did I fix it or did I just dream I did
