### ISSUE TITLE
[Request] Sort the lists of the classes in an organized way.

### ISSUE THREAD

**Issue by Rubyurek** [MKhayle/XIVComboExpanded#355]
I have noticed that the list of classes has become relatively confusing. Would it be possible to split up the class lists so that you know which spells belong to the single target combo and which to multi target? At the moment everything is mixed up :)

**Comment by kaedys** [comment]
Work is already in progress on this one.  MKhayle is actually working on a complete revamp of the UI that'll add this, as well as a number of additional organizational features (such as tabs instead of expanding sections for jobs)

**Comment by MKhayle** [comment]
Yes, this is featured in what's coming with #323
