### ISSUE TITLE
[Request][PLD] Replace Royal Authority/Prominence with Holy Spirit/Circle between levels 68 and 90.

### ISSUE THREAD

**Issue by Mely2k1** [MKhayle/XIVComboExpanded#356]
**Describe the feature you'd like**
Replace the Royal Authority and Prominence combo's with Holy Spirit and Holy Circle between the levels of 68 (when you get Requiescat) and 90 (when you get the Blade combo) while under the effect of Requiescat.  This is basically what happens once you get the Blade combo, but allows that functionality when sync'd below level 90.

Thanks!

**Comment by kaedys** [comment]
Mmm, I need to PR up my local fix/adjustment for that.  Holy Spirit _is_ used between those levels, but currently only gets prioritized if you're also under FoF, and it's common for one of the Req stacks to not fit in there before you get the full Blades combo.
