### ISSUE TITLE
[Bug] BRD : Perfect Rain of Death Feature doesn't work

### ISSUE THREAD

**Issue by strongerjersey** [MKhayle/XIVComboExpanded#357]
Title

**Comment by kaedys** [comment]
I just tested it locally, and it's working fine for me, so we're going to need more details.  Which combos do you have active?  What behavior are you expecting, and what behavior are you seeing?

With that feature enabled and Wanderer's Minuet active, as soon as I hit 3 on my gauge, Rain of Death is replaced with Pitch Perfect exactly as expected.

**Comment by MKhayle** [comment]
I haven't been able to reproduce the issue either with Perfect Rain of Death as the only enabled combo. It does work as intended.
