### ISSUE TITLE
[Bug] BRD #29 "Wanderer's Minuet Semi-Fix" feature not working

### ISSUE THREAD

**Issue by Zadanz** [MKhayle/XIVComboExpanded#360]
The description of the feature states "Turns Peloton into Wanderer's Minuet to Pitch Perfect while you have a target", however this is always the case, whether or not you have a target selected, thus Peloton is never available while this feature is enabled.
The slotted ability is Peloton.

Using plugin v1.5.1.9
Tested with Dalamud version 10.0.0.6 and 10.0.0.6-24-g818eec91

Issue appears even if this is the only enabled feature.
Not using any other XIVCombo fork.

With how the feature is worded, I expected the button to be Peloton when no target is selected/out of combat and Wanderer's Minuet/Pitch Perfect when a target is selected/in combat.

**Comment by MKhayle** [comment]
You are right, and also, this combo shouldn't actually be there anymore since it was used to fix an in-game issue during Endwalker which has been adressed since. I'll remove it from the list, but will add an Adventurer alternative for Peloton.

**Comment by Zadanz** [comment]
Ah, I see. I was wondering why it was called "Semi-fix".
Sounds good, just wanted to let you know. It seemed like a pretty good idea to replace Peloton with something while in combat since it only has use outside of it.

**Comment by MKhayle** [comment]
The Peloton feature replacement will be added in the rework (#323) and I'm removing this feature in the next update
