### ISSUE TITLE
[Bug] GNB Using Burst Strike Feature with Double Down Feature will use Double Down while icon shows Burst Strike

### ISSUE THREAD

**Issue by bfabe8** [MKhayle/XIVComboExpanded#364]
**Describe the bug**
When using both Burst Strike Feature and Double Down Feature, Solid Barrel will be replaced by Burst Strike when it would overcap - however, if Double Down is usable at this time, it will cast Double Down even though the icon shows Burst Strike.

In addition, I feel like either it shouldn't cast Double Down in these cases or there should be an option to keep Double Down from replacing Solid Barrel as it does here, in case CD alignments mean Double Down comes up before No Mercy etc.

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have
2. Which job is affected
3. What are your enabled combos for that job
4. Which skill is placed in your hotbar
5. Are you using any other XIVCombo fork? because you shouldn't

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by bfabe8** [comment]
Adding example:
https://github.com/user-attachments/assets/60905dbb-3177-47e2-b7df-5e64c57b9e35

**Comment by MKhayle** [comment]
Yeah, I had that issue for a long time and I think I know why it does that, I did notice it tho
I'll handle this after the #323

**Comment by MKhayle** [comment]
Hi! I haven't tackled this yet, but I'll do it soon now that #323 is done and v2 is out.

**Comment by MKhayle** [comment]
Hello! In order to fix it properly, I decided to split it into two options for Single Target & AoE, in a way which fixes this issue. 
This fix will be available in 2.0.0.9. 
Thanks for waiting!

**Comment by kaedys** [comment]
Isn't this a bit of a regression, though?  Now the replacement is strictly dependent on the other combos, and replaces the _combo_ buttons, rather than replacing Burst Strike and Fated Circle directly.

**Comment by MKhayle** [comment]
The issue was that having the Double Down feature enabled overwrote the Burst Strike and Fated Circle features, which displayed the icon for the latters while actually using the former _while in combo_, and that was unintuitive. 

Now that it's been split, we can actually re-add a separate feature which correctly does its job this time instead of overwriting Burst Strike and Fated Circle while combined with their parent combo and during their execution. I'll do that tomorrow, but that's something that had annoyed me for a long time since I did play GNB a lot and pressing a button to see a different action being executed is very frustrating.

**Comment by kaedys** [comment]
I don't even understand why the prior code worked that way.  When a combo preset is executed, if it returns a different action ID than the input, evaluation of all further features stops.  It should have been impossible for the main combo to replace to Burst Strike and then _that_ to be replaced by Double Down.  How was that occurring?

**Comment by MKhayle** [comment]
The plugin loops through every active combo in the order they are in the code, and the last actionID is the one getting replaced. However, the one being actually used is the first actionID that fits it iirc, and with the prior code, the actionID was getting replaced twice, I guess? I'm not 100% sure of it myself

**Comment by kaedys** [comment]
`TryInvoke`:
```
        var resultingActionID = this.Invoke(actionID, lastComboMove, comboTime, level);

        if (resultingActionID == 0 || actionID == resultingActionID)
            return false;

        newActionID = resultingActionID;
        return true;
```
and then `GetIconDetour`, where it's called:
```
            foreach (var combo in this.customCombos)
            {
                if (combo.TryInvoke(actionID, level, lastComboMove, comboTime, out var newActionID))
                    return newActionID;
            }
```

Unless I'm missing something, it just straight _stops_ as soon as any of the `Invoke` calls returns an ID that is non-zero and differs from the input ID.  I have no idea how that could be resulting in a different icon from the ability used, nor how it could apply multiple feature presets (that change the action) in succession.
