### ISSUE TITLE
[Bug] Glare III is not replaced with Glare IV; except when...

### ISSUE THREAD

**Issue by illutian** [MKhayle/XIVComboExpanded#365]
**Describe the bug**
'Glare4 Feature' does not cause Glare III to be replaced when Presence of Mind is active, and has Sacred Sight stacks.

Note: Glare III is on the '1' action button.

This is when the action Glare III dragged onto the action bar. However, I have a macro that uses:
/macroicon "Stone"
/ac "Stone"
/ac "Stone" ((target of target modifier; it breaks with the formatting here))

And this macro does get replaced with Glare 4.

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Version 1.5.1.11
2. White Mage
3. Afflatus Feature and Glate4 Feature; however this was present even with just Glare4 Feature active.
4. Glare III (as presented in the Actions UI)
5. No

**Expected behavior**
As with the macro, and other non-macros (ie Afflatus Feature replacing Cure II and Medica, it should replace the Glare III action with Glare IV.

**Screenshots or videos**
![ffxiv_07292024_114715_312](https://github.com/user-attachments/assets/93f09c69-65eb-4ceb-beda-b70ad6093387)

**Additional Context**

It appears that it works if you have Display Mode set to list all the abilities out and not set to the tree view. With the "list all" if you drag Stone the game changes it to Glare III and now Glare4 Feature will work on that, but continues to not work on the Glare III that is dragged from the "tree view" version of the Action UI.

Also noticed that Glare4 Feature only works on Stone, it will not change Stone II, III, IV, or Glare.

**Comment by MKhayle** [comment]
oh yeah, I see why

**Comment by MKhayle** [comment]
It's fixed in #323 (the `AttributesRework` branch) and will eventually be fixed when the rework will be pushed live

**Comment by MKhayle** [comment]
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!
