### ISSUE TITLE
[Request] Viper aoe

### ISSUE THREAD

**Issue by Samidaro** [MKhayle/XIVComboExpanded#367]
Hi, would it be possible to add an option that turns Steel Maw and Reaving Maw into Hunter's Den and Swiftskin's Den after using Vicepit and until used? Thanks

**Comment by MKhayle** [comment]
Hello, VPR has been heavily changed as of today and thus will require other priority changes, but I'll see if it can be taken into account

**Comment by kaedys** [comment]
I have combos pending for that, once we get #323 resolved, actually

**Comment by Samidaro** [comment]
That's amazing! Thanks so much

**Comment by MKhayle** [comment]
Will be live with 2.0.0.0's release

**Comment by MKhayle** [comment]
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!
