### ISSUE TITLE
[Bug] GNB fated circle cont.

### ISSUE THREAD

**Issue by ZachESN** [MKhayle/XIVComboExpanded#370]
after using fated circle the continuation skill replaces the normal AOE combo in addition to fated.

**Comment by kaedys** [comment]
Ah, yes, the [conditional for that](https://github.com/MKhayle/XIVComboExpanded/blob/master/XIVComboExpanded/Combos/GNB.cs#L208) isn't being properly wrapped in the `GunbreakerFatedCircle` feature check.  We'll need to shuffle the conditional ordering in that class so it acts properly.

**Comment by MKhayle** [comment]
Fixed in the rework, will be out with 2.0.0.0
