### ISSUE TITLE
[Request] Dissipation replaced with Aetherflow when Dissipation is unavailable

### ISSUE THREAD

**Issue by Jaesaces** [MKhayle/XIVComboExpanded#375]
**Description:**
If Disspation is not available, replace it with Aetherflow.  This happens under the following conditions:
    * When Dissipation is on cooldown
    * Summon Seraph is active
    * Fairy is not summoned
Rationale is that both abilities have the similar effect of granting 3 stacks of Aetherflow, so while one is unavailable it may be preferable to have another in its keybind.

**Alternative:**
Replace Dissipation with Energy Drain instead, which will allow you to use the "ED Aetherflow" option to achieve similar results while consolidating even more buttons.

**Comment by kaedys** [comment]
Interesting.  I actually think it probably makes _slightly_ more sense in the other direction, replacing Aetherflow with Dissipation if the former is on CD.  That said, due to the side effect of yeeting Selene/Eos out the window for the duration, and thus locking you out of all fairy-based abilities, is it really _wise_ to inadvertently hit Dissipation when you meant to hit Aetherflow but it was still on CD?

**Comment by Jaesaces** [comment]
Maybe, though the recommended opener for DT so far is to Dissipation before Aetherflow, so it might make sense to have both.

**Comment by Jaesaces** [comment]
Sorry, accidentally hit the close button.

**Comment by kaedys** [comment]
I don't especially mind the notion of a Dissipation -> ED combo.  Dissipation is almost _invariably_ used for DPS rather than healing anyway (except rare situations where you need a seriously chad Recitation spread and stack ALL the healing amps)

**Comment by Jaesaces** [comment]
And with Dissipation -> ED -> Aetherflow it works nicely with the SCH standard opener, which dissipates first, dumps them all on ED, then aetherflow and does the same

**Comment by MKhayle** [comment]
I'm definitely fine with it too, it will first wait on #323 though

**Comment by MKhayle** [comment]
Working on it!

**Comment by MKhayle** [comment]
It will be available along with 2.0.0.0's release
