### ISSUE TITLE
[Bug] DRG Combo Problems

### ISSUE THREAD

**Issue by GilgarazeHunter** [MKhayle/XIVComboExpanded#380]
Activating the Full Thrust Combo check box replaces both Full Thrust and Chaos Thrust with True Thrust, the same occurs when activating only the Chaos Thrust Combo check box. You can still only use the combo for whichever is activated though.

The "Chaos thrust Disembowel Option" is failing to disable True Thrust in the Chaos Thrust combo chain as described and instead works opposite of the description, with True Thrust being disabled while the Full Thrust combo chain is active. The same is true when using the Vorpal Thrust Option for the Full Thrust Combo.

**Comment by kaedys** [comment]
You don't perchance have the Double Chaos Thrust Combo and/or the Double Full Thrust Combo enabled, do you?

**Comment by kaedys** [comment]
Ya, ok, the Dragoon combo block is a bit complicated at the moment. I found the issue with the Disembowel and Vorpal Thrust options.  Also pretty sure I found the issue with the main combos.  Uno momento.
