### ISSUE TITLE
[Bug][VPR] Fangs no longer swapping automatically 

### ISSUE THREAD

**Issue by wittyHippie** [MKhayle/XIVComboExpanded#385]
It appears since the update that the two base  fang skills are no longer alternating with the secret mode. Sorry if this was addressed elsewhere or if it was intentional.

**Comment by MKhayle** [comment]
Yeah, this is because of the 7.05 patch. A bigger scale rework is on the way (cf #323)

**Comment by kaedys** [comment]
This should have been fixed by #366, though

**Comment by MKhayle** [comment]
(I haven't pushed a live version for a while, that's why)

**Comment by MKhayle** [comment]
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!
