### ISSUE TITLE
[Request] [RDM] Make Prefulgence over Redoublement a sub-option

### ISSUE THREAD

**Issue by ShroudedMuridian** [MKhayle/XIVComboExpanded#387]
**Describe the feature you'd like**
Remove Prefulgence from combo `#201`, restoring it to its functionality from Endwalker.

**Describe alternatives you've considered**
Add a sub-option to add Prefulgence to the end of this combo chain, for people who still want it.

**Additional context**
In Dawntrail, Prefulgence was added as a finisher after a full capstone combo under Manafication. Accordingly, XIVCombo was updated to add Prefulgence after Resolution as part of this combo chain. Unfortunately, there are several problems with this feature. 

Firstly, unlike the rest of the skills in this chain, Prefulgence is not a GCD activated by combo actions. It is an oGCD activated by a buff, which means that this feature can lead to unintended weaving when using this button.

More importantly, because of Manafication's 110s cooldown, there are many situations where we **do not want** to weave Prefulgence immediately after Resolution, instead holding it to use under raid buffs due to its extremely high potency. In these situations, this combo feature actually **prevents us from using our Melee combo if the Prefulgence buff is up.**

This feature only makes sense if you consider Prefulgence to be simply another button tacked onto the end of RDM's resource spender combo. In reality, it is not used this way in higher-level content, making this previously-useful feature actively detrimental at higher levels of play.

For additional information on how Manafication/Prefulgence work in Dawntrail, see this guide: https://docs.google.com/document/d/1Z3dw4SsbXqtTmXSq7q2aWzghFaLJxeNg_E0lp-d63zU/edit#heading=h.n62g4oh3ugbk

**Comment by MKhayle** [comment]
Oh, that's a totally fair point. I'll make it an optional feature, yes yes.

**Comment by ShroudedMuridian** [comment]
Thanks! Your work on this plugin is much appreciated.

**Comment by kaedys** [comment]
Gods, they need to just shift Manafication back to a 120s CD and be done with it.  The only reason it was reduced to 110 in the first place is because you sometimes needed to hold it if you were already over 50/50 mana, and that gave you up to a 20s window (stealing 10s each from the prior CD and the next one) to handle that.  But since it no longer grants mana, the reduce CD is just a mess from an optimization standpoint and feels terrible.

**Comment by MKhayle** [comment]
Taking care of that one

**Comment by MKhayle** [comment]
Should be available with 2.0.0.0's release

**Comment by MKhayle** [comment]
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!
