### ISSUE TITLE
[Request][Planned] DRK Disesteem Feature and Secret Combo for Delirium Overcap

### ISSUE THREAD

**Issue by lhn1703** [MKhayle/XIVComboExpanded#393]
Creating an issue to track DRK dawntrail enhancements. As my DRK is currently level 93 I have no realistic way to test this yet. I will get around to this when I level my DRK to 100 unless anyone else wants to implement it first.

1. Accessibility: update living shadow features to turn Bloodspiller/Quietus <- Disesteem at lvl 100 and appropriate.
2. Accessibility: soul eater/stalwart soul <- disesteem at lvl 100 when appropriate.
3. Secret: gauge overcap option at 70 if Delirium is about to be off cooldown since the next 3 delirium gcds will generate 10 gauge each.

**Comment by kaedys** [comment]
Also recommend a separate feature to put Disesteem on the main Souleater combo when available, so it doesn't get forgotten (but I can almost guarantee you I'll forget it >.>)

**Comment by lhn1703** [comment]
Ok, so I have a branch with this, but for the life of me I cannot get the disesteem feature to work. Maybe @MKhayle or @kaedys can take a look at my branch and correctly implement the syntax? I got the combo presets done however. 

https://github.com/lhn1703/XIVComboExpanded/commit/cdccb32bcb1fc1f5af6c8b3ece2fed3a38178a78

**Comment by lhn1703** [comment]
nvm I feel dumb.
