### ISSUE TITLE
[Request] RPR Enshround Communio Feature turns into Perfectio

### ISSUE THREAD

**Issue by HPDeskJet2540** [MKhayle/XIVComboExpanded#395]
**Describe the feature you'd like**
Right now on RPR by game default the Communio button will turn into Perfectio, Enshround Communio Feature should have the Enshround buttion turns into Perfectio as well
**Describe alternatives you've considered**
Arcane Cirle into Plentiful Harvest (already in) into Perfectio as well
**Additional context**
Add any other context or screenshots about the feature request here. Mock-ups are fine too.

**Comment by kaedys** [comment]
So, your alternative is actually handled by a PR I just put in a few minutes ago, #394, which is related to issue #352.  I don't see any reason the Enshroud Communio button can't also have a feature for including Perfectio.  I'll add it to 394.

**Comment by kaedys** [comment]
Added.  I actually didn't even link it to the Enshroud Communio feature, because I don't see any reason Enshroud can't just independently turn into Perfectio even without that feature on.

**Comment by MKhayle** [comment]
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!
