### ISSUE TITLE
[Bug] Warrior Storm's Path Combo is comboing into Storm's Eye instead

### ISSUE THREAD

**Issue by Rhadgar** [MKhayle/XIVComboExpanded#397]
**Describe the bug**
When selecting Storm's Path Combo (only one selected for single target) it changes the final button into Storm's Eye instead.

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. 2.0.0.1
2. Warrior
3. Storm's Path Combo, Mythril Tempest Combo, and Primal Release Feature
4. Storm's Path
5. Are you using any other XIVCombo fork? No

**Expected behavior**
Heavy Swing > Maim > Storm's Path

**Comment by MKhayle** [comment]
Indeed, I can reproduce it. It's because it was lacking a condition in the code's logic and was only working when you had > 30sec of Surging Tempest buff left. 
I fixed it in 2.0.0.2 which will soon be out https://github.com/MKhayle/XIVComboExpanded/commit/09c62fb775e3a5d7ac0a08f725fdf5170b84b0cf
