### ISSUE TITLE
[Request] A small suggestion for White Mage

### ISSUE THREAD

**Issue by movildima** [MKhayle/XIVComboExpanded#398]
It would be awesome if it would be possible to add Glare IV over Holy when available as an option, for AOE scenarios, or to have it as a separate button in single target.

**Comment by MKhayle** [comment]
Oh, sure. Didn't notice Glare IV was actually an AoE.

**Comment by movildima** [comment]
Oh and as I remembered just now, Psyche over Dyskrasia would also be awesome!

**Comment by MKhayle** [comment]
2.0.0.3 has both of those. https://github.com/MKhayle/XIVComboExpanded/commit/63d729a0a2511245c490f4d44d542a18947ddfa1

Yey!

**Comment by movildima** [comment]
That was incredibly quick dang, thank you so much for your work!
I just noticed though that the last SGE addition does not overwrite Dyskrasia II. I assume it's a quick fix so just commenting here so you can see.

**Comment by MKhayle** [comment]
Yeah, it was my bad, I just pushed an update to fix it a second ago. 2.0.0.4 should fix it appropriately.
