### ISSUE TITLE
[Request]change sentence for description of accessibility combo

### ISSUE THREAD

**Issue by Xelfen** [MKhayle/XIVComboExpanded#400]
i suggest deleting the sentence "howerer they definitely won't make you a better player" which is not appropriate for forms of accessibility.

I also suggest to modify the first sentence with these terms "very non-optimal" or maybe "extremely non-optimal"

**Comment by MKhayle** [comment]
This was intended as a warning for players who are looking for fully automated rotations rather than those who'd require accessibility. 
I understand the issue that it may however rise and will re-think about the phrasing.

**Comment by MKhayle** [comment]
![image](https://github.com/user-attachments/assets/80751365-c653-48d7-9c5f-19f6263bb626)

I think this phrasing may feel less judgemental and more accurate. 
I also have the constraint of limited space in that box, so I can't change the first sentence as much as I would, but I feel the last sentence's replacement is enough to convey the message.

**Comment by MKhayle** [comment]
I will push it with the next batch of bugfixes, as to avoid spamming users with constant updates if I can avoid it.

**Comment by MKhayle** [comment]
Changes pushed in 2.0.0.4, thanks for the adequate suggestion!
