### ISSUE TITLE
[Bug] WAR Auto-surge bugging

### ISSUE THREAD

**Issue by Psukhais** [MKhayle/XIVComboExpanded#401]
**Describe the bug**
Even with auto-surge unchecked everywhere, it still force itself in the combo system
**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
Simply start a fight with auto-surge unchecked, and try to do a storm path combo
**Expected behavior**
Storm path combo should not transform into surge 

**Additional context**

**Comment by MKhayle** [comment]
Hello, can you update to the latest version so we can check it's not a duplicate of #397 ?

**Comment by Psukhais** [comment]
Sure, just did, still have the issue !

**Comment by Psukhais** [comment]
In fact it's even weirder. If I have no surge running, everything work great. As soon as surge work, it break, and if surge is <30 sec it will ignore every setting and just force me into storm eye

**Comment by MKhayle** [comment]
@kaedys I summon thee

**Comment by MKhayle** [comment]
Can you also check your current version, because you may have missed the previous update by like, 5 minutes

**Comment by Psukhais** [comment]
If you guys have a discord, I dont mind joining and screen sharing to make sure the problem is not me being a dumbass btw ! Also, I must say, so far i just love this plugin !

**Comment by Psukhais** [comment]
Fixed ! Yes I missed it by like two or three minutes XD
You guys are awesome ! Thanks !

**Comment by MKhayle** [comment]
Perfect, thanks!
