### ISSUE TITLE
[Request] [AST] Mouseover for Play I, Play II, Play III

### ISSUE THREAD

**Issue by Rubyurek** [MKhayle/XIVComboExpanded#405]
It would be time-saving and practical if these three abilities could have a direct mouseover so that you don't have to click away your actual target.

**Comment by MKhayle** [comment]
Hi! Thanks for the suggestion, but it is totally out of scope for XIVCombo. You should use another plugin dedicated for this usecase, like MOAction or ReAction (3rd party).
