### ISSUE TITLE
[Bug] Generation Legacy followup VPR

### ISSUE THREAD

**Issue by ZachESN** [MKhayle/XIVComboExpanded#406]
the option only replaces First and Second Generation with legacies. third and fourth are not replaced

**Comment by MKhayle** [comment]
Hi, which Generation Legacy combo are you mentioning? 
The All-in-one Reawaken Feature worked perfectly fine on my end while testing, but I couldn't check myself for the Generation Legacy Feature as I am not yet VPR lvl 100. Is it that one?

**Comment by masanbol** [comment]
AIO works fine - i'll try out the other shortly to confirm

**Comment by kaedys** [comment]
I just tested the AIO, and then also separately the Generation Legacy Feature.  Both work exactly as expected on the buttons noted.  _However_, if one is using the Steel Coil feature that puts Hunter's Coil and Swiftskin's Coil onto the Fangs buttons, _that_ one is not currently working.  I have a fix ready for it, though.

**Comment by masanbol** [comment]
Aha, that explains why I missed it. Do those need to be exclusive?

**Comment by kaedys** [comment]
Nope, just need a special handling block for 3rd and 4th within the Steel Coil feature block.  I've got a fix locally that I just tested and is now working as expected.

**Comment by ZachESN** [comment]
Awesome thanks
