### ISSUE TITLE
[Bug] Moving the Settings window offscreen and then back changes the background to white

### ISSUE THREAD

**Issue by Nelpheras** [MKhayle/XIVComboExpanded#408]
Dragging a portion of the Settings window offscreen hides all content.
Moving the window back in reveals everything again but the background of all the sub-windows is now white, making it hard to read the Combos section and impossible to read the Settings and Changelog sections.
AFAIK this only happens with XIVComboExpanded.
It does not happen when minimizing the window with the arrow.

Also the About section vanishes when the Changelog section is selected 🤨

edit: this only happens when moving the left side of the window offscreen (probably the icons?)

Offscreen:
![offscreen](https://github.com/user-attachments/assets/35773ff0-c4eb-4a68-a847-da083bf0255e)

Back in:
![backin](https://github.com/user-attachments/assets/d490893f-2b91-4a65-8b89-a2d79cffaf94)

Houdini:
![ded](https://github.com/user-attachments/assets/74b071c8-1f8b-457f-9e22-8a70b4c93805)

**Comment by MKhayle** [comment]
Alright, figured out the issue.
I'll fix that asap as that breaks Dalamud styles entirely. 
You have the auto-select setting enabled and were playing a DoH job when you opened the window, which then caused that issue. 
Fixing it in 2.0.0.5, which should be out very soon.

**Comment by MKhayle** [comment]
2.0.0.5 is out and should fix this. Thanks for opening this issue, because I haven't played crafter for a while!

**Comment by MKhayle** [comment]
(you can fix this either by restarting your game or changing your dalamud style in the dalamud settings)

**Comment by MKhayle** [comment]
Under which conditions does this happen so I can try reproducing?

**Comment by MKhayle** [comment]
Oh, I have an idea of what is going on.

**Comment by Xelfen** [comment]
when I move the window to the left, off-screen, on the right I don't have this problem

**Comment by MKhayle** [comment]
You're using a class (not a job) & the auto-job selection assigns you to an unsupported job (since classes aren't job)
I'm fixing this tonight, sorry that it happens

**Comment by Xelfen** [comment]
i've been testing jobs that don't have classes at the base, i also have this problem, and it also does it on the starting screen, or whether a class of 2.5 or less at its job crystal or not, this is for my tests, maybe it can help

**Comment by MKhayle** [comment]
Yes, once the issue arises it's "leaking" to the rest of Dalamud's imgui windows. It shouldn't happen and I obviously didn't check it enough.
What is displayed on top of the window when you have this issue? Which job name is displayed?

**Comment by Xelfen** [comment]
the display is identical that has to post, i tested with the starting screen+ job displayed by default on the plugin: paladin = same issue
sage + job displayed : sage  = same
reaper + job displayer : pictomancer = same

![image](https://github.com/user-attachments/assets/731f78c0-63d0-4da5-b658-055f1e355b5e)

**Comment by kaedys** [comment]
@MKhayle had this happen to me when I accidentally dragged the window partially off screen ( do not have multi-monitor enabled in Dalamud).  I tried a rebuild (fixing another feature), and it made the whole mod window full white, then crashed the game to desktop without error in the log or a crash log file about 10 seconds later.

**Comment by Xelfen** [comment]
problem solved, thanks ! ^^
