### ISSUE TITLE
[Request] RDM: Option to Replace Jolt with Grand Impact when available.  

### ISSUE THREAD

**Issue by Felunya** [MKhayle/XIVComboExpanded#411]
Sorry :)

As the description said, I was wondering if it is possible to replace Jolt with Grand Impact whenever it is possible. 
It does it automatically in the opener for Redmage, but later it only replaces Manafication. 

I deleted the request because I felt a bit silly to ask for a feature to avoid only one extra button press :)

Thank you for the amazing plugin and hard work <3 :)

**Comment by MKhayle** [comment]
Isn't that a native feature...?
![image](https://github.com/user-attachments/assets/f60a7c11-865a-43e8-8f4f-9009d3e319e8)

**Comment by kaedys** [comment]
Um...doesn't Grand Impact _natively_ replace Jolt?  Like, in the base game?  I know the existing Verstone/Verfire features (both the regular and 'plus' versions) already have special handling for it as well.

**Comment by kaedys** [comment]
Note that Manafication is replaced by Prefulgence, not Grand Impact.

**Comment by Felunya** [comment]
I'm...an idiot. 
I'm so sorry for wasting your time. I sat here for 30 minutes trying it around and was wondering about it. My brain is heat fried... 

*goes into hidng*

**Comment by kaedys** [comment]
Haha, no worries

**Comment by Felunya** [comment]
Thank you <3 

And thanks again for the amazing plugin :)
