### ISSUE TITLE
[Request] expand the GNB expanded continuation feature

### ISSUE THREAD

**Issue by ZachESN** [MKhayle/XIVComboExpanded#412]
i think it would be a nice addition to be able to choose which parts of the expanded cont feature the player would like to use.

make it a sub option to turn keep on or turn off the different options. kinda like the DRG or SAM melee options

ex: being able to use some of the feature to get the danger zone and the reign of beasts parts but not the other parts.

**Comment by MKhayle** [comment]
I will consider this, yes. This isn't unreasonable at all, and may not be long to do, if that's just splitting things.

**Comment by MKhayle** [comment]
![image](https://github.com/user-attachments/assets/29fcd0e6-4e48-4b1b-be2d-5fd02e20bd66)
2.0.0.8 has been pushed and should be soon available with the aforementionned changes.
