### ISSUE TITLE
[Request] SGE: Psyche on Phlegma

### ISSUE THREAD

**Issue by fineanddandy26** [MKhayle/XIVComboExpanded#413]
Pretty self explanatory, I feel like it would be helpful to have it on Phlegma, as currently the option exists to put it on Dosis, Dyskrasia, and Toxikon, but not Phlegma.

Edit: Also, too late to put in the title, but I think Toxikon->Psyche/Dosis->Psyche should be their own feature, rather than having to have Toxikon->Phlegma/Dosis->Enhanced Dosis enabled first.

**Comment by MKhayle** [comment]
I knew I should have made a "PSYCHE EVERYWHERE" feature.

**Comment by MKhayle** [comment]
(this is a joke, I'm taking this into account as Psyche is available on every offensive spell but Phlegma right now)

**Comment by MKhayle** [comment]
2.0.0.8 should have added Phlegma into Psyche, and also, please don't edit posts because I missed it and I'll have to get back to SGE ;_;

**Comment by fineanddandy26** [comment]
I think you might have accidentally removed the other [Blank]->Psyche features. It looks like only Phlegma->Psyche exists now.

**Comment by MKhayle** [comment]
Are you checking the Accessibility/Secret tabs?

**Comment by MKhayle** [comment]
(the children "issue" will be fixed with 2.0.0.9, but since I already pushed an update, that will wait a bit)
