### ISSUE TITLE
[Request] VPR consistent positional buttons

### ISSUE THREAD

**Issue by Lunatory** [MKhayle/XIVComboExpanded#414]
**Describe the feature you'd like**
When the player has the Hindstung Venom buff, can you replace Hindsbane Fang with Hindsting Strike, and when the player has the Flanksbane Venom buff, can you change Flanksting Strike to Flanksbane Fang? I attached an image to show what I mean

**Additional context**
![feature req](https://github.com/user-attachments/assets/4ef50484-318b-4942-a143-26eae5279a7c)

**Comment by MKhayle** [comment]
#390 should add back that if I'm not mistaken @aldros-ffxi ?

**Comment by MKhayle** [comment]
It used to be a feature until the 7.05 mini-rework and we had to temporarily disable it as it was relying on Noxious Gnash for its logic, iirc

**Comment by Lunatory** [comment]
"Auto Steel Reaving" does this for the first hit, but I don't see an option to do this for the 3rd hit, unless the linked pull isn't live yet.

**Comment by MKhayle** [comment]
It isn't live yet indeed, it's a pull request which is being worked on!

**Comment by Lunatory** [comment]
thanks! I will wait for it to be pushed to live then.

**Comment by kaedys** [comment]
390 _sorta_ does this.  It makes Steel Fangs just have the entire rotation on it across the board.  I put together a separate feature that just applies to the 3rd combo hit, for those that still want both Steel and Reaving on their bar.
