### ISSUE TITLE
[Bug] VPR - Reawaken not changing Generations and Legacys

### ISSUE THREAD

**Issue by baelrayneVessdren** [MKhayle/XIVComboExpanded#425]
Greetings.

Using Reawaken triggers the 1st Generation / 1st Legacy combo, but it does not advance to 2nd, 3rd, etc. It stays on 1st. 

**Option is set:**
![image](https://github.com/user-attachments/assets/34d1fafd-d1d3-4778-8e98-78b69101adef)

**Global settings:**
![image](https://github.com/user-attachments/assets/8b2dd8ff-ccaf-42fa-805e-75e0a8a9fc24)

Thanks for your hard work.

Regards

**Comment by kaedys** [comment]
The Generation Legacy feature is not intended to put all of them on the same button, all it does is add each Legacy to the same button that had that Generation.  So Steel Fangs becomes First Generation and then First Legacy, and that's it.  Reaving Fangs becomes Second Generation and then Second Legacy.

If you want the entire combo on one button, you need the `All-in-one Reawaken Feature`, which puts the entire combo, including the Legacy oGCDs, onto Reawaken itself.  It's flagged as an Accessibility option (as are most features that compress that automate sequences like that), so you'll need to enable Accessibility Combos in your Settings tab:

<img width="525" alt="20240813-163256-c553cd" src="https://github.com/user-attachments/assets/37f24bd9-f442-4bfe-b0c2-c1724a127fd3">

**Comment by baelrayneVessdren** [comment]
Interesting .... Not only your combo options but your settings as well look a little different from mine:
![image](https://github.com/user-attachments/assets/7bea4aa8-1e5c-4161-a119-44c1237a73bb)

**Comment by kaedys** [comment]
The Secret box only shows up when you enabled the Accessibility checkbox

**Comment by baelrayneVessdren** [comment]
Just found that out :D Thanks alot though. That also (probably, most likely) solves the bug.

**Comment by baelrayneVessdren** [comment]
No it doesn't .... Since the two options conflict with each other :(

**Comment by baelrayneVessdren** [comment]
Nvm. I was stupid. Didn't think the chain through. Deleted the comment
