### ISSUE TITLE
[Request] VPR - Merging Twinfgang / -blood into one button

### ISSUE THREAD

**Issue by baelrayneVessdren** [MKhayle/XIVComboExpanded#426]
Greetings.

Is it possible to merge Twinfang & -blood into one button? Maybe as an additional option for oGCDs?

The behavior might look somewhat like Standard Combos. After using Vicewinder > Coil > Start the Twin-button with either combo and switch accordingly. Not a one button combo like Standard. Rather a two button like 1-1-2-2. 

**As a far away afterthought (just to make it a little more busy):**
If feasible in terms of work involved: Tail / Fang / Blood into one "Finisher" button and a sub option for Standard Combos to not finish on Tail, but rather just go through the initial 1-1-1 and have the finisher button separately for 1-1-1-2. 

Thanks for all your hard work.

Regards

**Comment by kaedys** [comment]
That option already exists.
<img width="474" alt="20240813-162720-efa36d" src="https://github.com/user-attachments/assets/8a8d711b-449d-4b36-8b95-7123b78b5903">

There are also combo options for everything that has a Twinfang or Twinblood followup (Specifically, the Coils after Vicewinder, the Dens after Vicepit, and Uncoiled Fury) to include those followups on the same button when they're available.  Same for including the Serpent's Tail followups on the buttons that trigger them, features for those already exist as well.

**Comment by baelrayneVessdren** [comment]
Not in my version (v2.0.0.10), which is (according to Dalamud) the latest:
![image](https://github.com/user-attachments/assets/dead93ab-2779-4482-bb6e-84c8226a3a98)

**Comment by kaedys** [comment]
As with the other issue, you need to enable Accessibility combos to see it.
