### ISSUE TITLE
[Bug] VPR - Serpent's Ire on Reawaken changes ALL buttons to Serpent's Ire

### ISSUE THREAD

**Issue by baelrayneVessdren** [MKhayle/XIVComboExpanded#427]
Hi Kaedys (probably the one answering :D )

This one seems legitimate though since it does not seem to have any conflicts listed.

Serpent's Ire on Reawaken changes all my buttons to active Serpent's Ire instead of only Reawaken (works fine for Fury and Ire):
![image](https://github.com/user-attachments/assets/c315a93e-ee09-43d8-94cb-fc69757290fb)

I tried rotating through the other options but the effect stayed. Does not seem intended. 

Thanks for the great help earlier and for all the hard work.

Regards

**Comment by MKhayle** [comment]
I legit thought that was a loss meme at first

**Comment by baelrayneVessdren** [comment]
It looks like it, doesn't it :D But no, I am afraid not.

**Comment by kaedys** [comment]
Someone's channeling MKhayle's "you WILL Lucid Dream and you will like it" feature =P

**Comment by kaedys** [comment]
<img width="664" alt="20240813-171327-d9f3ba" src="https://github.com/user-attachments/assets/0c4727dc-1e37-473d-b6ee-8a555e765910">

Well that's an oops =P

**Comment by MKhayle** [comment]
I'll fix that in the next update, don't PR a fix @kaedys

**Comment by MKhayle** [comment]
fixed in 2.0.0.11 https://github.com/MKhayle/XIVComboExpanded/commit/c4e27c23c30f098f572c00942c65bf7e2838e21a
