### ISSUE TITLE
[Request] DRG: Geirskogul to Wyrmwind Thrust - Prioritize Wyrmwind Thrust

### ISSUE THREAD

**Issue by fineanddandy26** [MKhayle/XIVComboExpanded#430]
Title. Right now, how the Geirskogul to Wyrmwind Thrust Feature works is that it only replaces Geirskogul when both Geirskogul and Nastrond are on cooldown. While not replacing Geirskogul makes sense, I don't see why it should wait for all three Nastrond stacks. Nastrond is a lot more lenient, giving you three OGCD stacks you can use anytime within a 20 second Geirskogul window. On the other hand, I find it far more likely a Dragoon could end up 1 GCD away from overcapping Firstmind's Focus upon entering a burst window, and need to prioritize Wyrmwind's Thrust.

**Comment by MKhayle** [comment]
![image](https://github.com/user-attachments/assets/929e0f29-851f-4008-abcc-0b18c409b656)
work in progress

**Comment by fineanddandy26** [comment]
I can't believe I've been using a plugin made by the _french_ /s

**Comment by kaedys** [comment]
Ya, it should definitely default to Geirskogal > Wyrmwind > Nastrond.  I can fix this when I get back next week, I've got DRG at 100.
