### ISSUE TITLE
[Bug] Swift Raise Feature not working

### ISSUE THREAD

**Issue by whosteen** [MKhayle/XIVComboExpanded#431]
**Describe the bug**
Egeiro gets replaced by Swiftcast, but does not become Egerio after Swiftcast is used.  Seems to be broken for all Raises.  (Tested all but BLU)

**To Reproduce**
XIV Combo Expanded, Sage, Swift Raise, Variant Raise, Automatic Dreams, Auto Eukrasian Dosis, Phlegma into Toxicon.  Egeiro placed on hotbar.

**Expected behavior**
Swift should become raise ability.

**Screenshots or videos**

https://github.com/user-attachments/assets/250e91d4-2650-4e21-becf-cdedec6b3d78

**Additional context**

**Comment by kaedys** [comment]
@MKhayle did you double-check that `CanUseAction` actually replicates the functionality of `IsCooldownUsable`, in addition to checking proper usability?  That's the only thing I can think of that might be causing this.

**Comment by MKhayle** [comment]
Yeah, I also think that's what happening. I guess the failsafe I added ended up causing a failure.

**Comment by MKhayle** [comment]
2.0.0.12 fixes that issue. Sorry again!
