### ISSUE TITLE
[Bug] Automatic Soul Slice [Reaper]

### ISSUE THREAD

**Issue by XannnaGG** [MKhayle/XIVComboExpanded#435]
### **Reaper Melee**
It would seems that Automatic Soul Slice for Reaper works as it should if you are in a duty where it is available, alas should you enter a low level dungeon. It remains greyed out on top of the spells it replaces, meaning that to use the spells that it replaces, you would have to disable the Automatic Soul Slice. 

I have the Slice combo and Scythe combo active already so I only press 1 and 2 for my single target and my Aoe. Also have Slice Gallows Feature turned on. I was wondering if it can be fixed so that my Automatic Soul Slice does not change my spells if it is not available to be used based on the level it requires. So if I don't fullfill the level requirements for the spells, it doesn't change into them? It was a pain to figure out mid a low level dungeon why I suddenly couldn't attack because Soul Slice and Soul Scythe were replacing my spells even when the duty was lower level.

-----------------------------------------

### I am using:
•Slice Combo
•Scythe Combo
•Soul Reaver Gluttony Feature
•Automatic Soul Slice _(The issue)_
•Slice Gallows Feature
•Enshroud Communio Feature
•Arcane Harvest
•Regress Feature

-----------------------------------------

XIV Combo Expanded v2.0.0.12

-----------------------------------------

I just want Automatic Soul Slice to not replace my spells if the level requirements are not met, otherwise you have to constantly turn it off for you to be able to attack in low level duties.

If it wasn't clear, I am playing **Reaper**

**Comment by MKhayle** [comment]
@kaedys we need more level sync checks in general I guess

**Comment by kaedys** [comment]
Yep, damnit, forgot to include a level check in that conditional >.<

**Comment by XannnaGG** [comment]
I am wondering if the update has hit yet or if I missed it?

**Comment by MKhayle** [comment]
it's merged but I have yet to push a release, sorry for the delay! I have a kinda big backlog and need to sort out things before sending an update to avoid issues/broken stuff

**Comment by XannnaGG** [comment]
Ah okay! Don't worry and no need to be sorry! I was simply worried mine had not updated yet or if I had missed something! Thank you for clarifying!
