### ISSUE TITLE
[Other] / command to open menu?

### ISSUE THREAD

**Issue by GoodnightMoon4** [MKhayle/XIVComboExpanded#436]
Am I crazy or is there no / command to open this plugin? I know the older, original combo plugin used /pcombo, but that doesn't work for this one.

**Comment by XannnaGG** [comment]
It works for me /pcombo works for me

**Comment by MKhayle** [comment]
The command is `/pcombo`, however it may conflict with other forks or the original XIVCombo if you have it installed.
