### ISSUE TITLE
[Bug] VPR: Twin Coil Feature Replaces Vices

### ISSUE THREAD

**Issue by Propagandist1** [MKhayle/XIVComboExpanded#439]
**Describe the bug**
When the Twin Coil Feature is enabled, the Vicewinder and Vicepit abilities will be replaced with Twinfang and Twinblood under certain conditions.  After using Vicewinder, and then after using either Swiftskin's Coil or Hunter's Coil, all three of these abilities turn into Twinfang/Twinblood.  Similarly, after using Vicepit, and then after using Swiftskin's Den or Hunter's Den, all three of these abilities turn into Twinfang/Twinblood.  

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have: 2.0.0.12
2. Which job is affected: VPR
3. What are your enabled combos for that job: Just Twin Coil Feature for this test
4. Which skill is placed in your hotbar: Vicewinder, Swiftskin's Coil, Hunter's Coil for this test
5. Are you using any other XIVCombo fork? because you shouldn't: Nope!  Expanded is all we need!

**Expected behavior**
After using Vicewinder, and then after using either Swiftskin's Coil or Hunter's Coil, only Swiftskin's Coil and Hunter's Coil turn into Twinfang/Twinblood.  

After using Vicepit, and then after using either Swiftskin's Den or Hunter's Den, only Swiftskin's Den and Hunter's Den turn into Twinfang/Twinblood.  

In this way, one would still see the charges/cooldowns on Vicewinder/Vicepit while executing the combo.

**Screenshots or videos**

![image](https://github.com/user-attachments/assets/cfb5ae6a-ec81-4e07-9440-2870e2b847d2)
![image](https://github.com/user-attachments/assets/32fc0fbe-f618-4968-98ff-8cda7c0d21d2)
![image](https://github.com/user-attachments/assets/3a81623f-3203-4644-9973-fbdeb777724d)
![image](https://github.com/user-attachments/assets/20a8a900-7add-4d86-a845-b3a500e4fada)

**Additional context**
This also happens when Steel Coil Feature is enabled in addition to the Twin Coil Feature.  I wanted to have my left/right combos turn into the Coils/Dens, and then Twinfang/Twinblood when using Vicewinder.  And they do!  But Vicewinder changes, too.  It seems like that is undesired behavior, perhaps best enabled with a sub-option.

**Comment by kaedys** [comment]
Already fixed in #438

> (VPR) The replacement of Vicewinder and Vicepit with the Twincoil Feature oGCDs now only occurs if the PvP combo for Winder/Pit is also enabled.

**Comment by Propagandist1** [comment]
Sweet!  Thank you.  Closing the issue.
