### ISSUE TITLE
[Request] VPR: Twin Coil Feature Alternative

### ISSUE THREAD

**Issue by Propagandist1** [MKhayle/XIVComboExpanded#440]
**Describe the feature you'd like**
When Vicewinder is pressed, I'd like for Twinfang to only replace the "left" or "flank" abilities when requirements for execution are met, while Twinblood only replaces the "right" or "rear" abilities when requirements for execution are met.  So Hunter's Coil and Swiftskin's Coil would change to Twinfang and Twinblood, respectively, rather than both of them changing to either Twinfang OR Twinblood, depending on the proper order. 

Similarly Vicepit is pressed, I'd like for Twinfang to only replace Hunter's Den and for Twinblood to only replace Swiftskin's Den.

This would serve a similar function to the Twin Coil feature, but would enable more left/right interaction during the combos.

**Describe alternatives you've considered**
The current Twin Coil Feature is already a viable alternative.  

**Additional context**
Here's a visual representation of the desired behavior.  If the Steel Coil feature is also enabled, this would also apply to the main "left/right" combos.  Could keep things pretty cleanly on just your left/right combo buttons.  Lots of consolidation, but still facilitating control over left/right for the flank/rear positionals.

![image](https://github.com/user-attachments/assets/bf5ea51b-ea0d-4c7d-a588-83b183f3d440)

**Comment by kaedys** [comment]
This was actually how the Twins on the Coils feature was originally implemented, iirc.  Shouldn't be too tough to add a feature to support this.

**Comment by Propagandist1** [comment]
Thank you for the response!  If it's too much trouble, like I said, the current Twin Coils Feature functions.  But this would allow there to still be left/right differentiation, kind of like how RDM's combos and RPR's combos are.

**Comment by MKhayle** [comment]
> This was actually how the Twins on the Coils feature was originally implemented, iirc. Shouldn't be too tough to add a feature to support this.

thanks for volunteering!
