### ISSUE TITLE
[Bug] Monk Meditation Features not properly syncing to pre-upgrade versions

### ISSUE THREAD

**Issue by corsair980** [MKhayle/XIVComboExpanded#441]
**Describe the bug**
Monk's Forbidden Meditation does not properly change to Steeled Meditation when synced below lvl 54 but at or above level 15 when outside of combat and Fifth Chakra not open with Bootshine Steeled Meditation sub-feature of Opo Feature active; instead, button returns "Action Not Yet Learned" when pressed outside of combat as Forbidden Meditation does not properly sync down

Possibly related but separately, the Enlightened Meditation feature in the Monk AOE Combo Feature group does not seem to work properly either as Masterful Blitz is never replaced at all by Inspirited Meditation or even the "not yet learned" Enlightened Meditation when synced below level 74 but at or above level 40 and outside of combat without Fifth Chakra opened

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have - v 2.0.0.12
2. Which job is affected - Monk
3. What are your enabled combos for that job - Opo Feature with all sub features, Raptor Feature, Coeurl Feature, Riddle of Brotherly Fire, Riddle of Brotherly Wind, and Monk AOE Combo Feature with all sub-features 
4. Which skill is placed in your hotbar - Bootshine/Leaping Opo for Opo Feature and sub-features, Masterful Blitz for Monk AOE Combo Feature and sub-features
5. Are you using any other XIVCombo fork? because you shouldn't - No

**Expected behavior**
Steeled Meditation, not Forbidden Meditation, should replace Bootshine and be available outside of combat without Fifth Chakra opened when synced at or above level 15 and below level 54. Same should be true for Inspirited Meditation replacing Masterful Blitz synced at or above level 40 and below level 74, however in this case the button needs to properly change to Inspirited Meditation instead of not changing at all

**Comment by kaedys** [comment]
I'm not surprised, I don't believe those features ended up getting updated for the like 3 different version of each of the two Meditations that now exist.

**Comment by MKhayle** [comment]
oof, that's a synchronization issue I probably forgot about
but also like kaedys said, they made a mess with meditation
I'll look into it

**Comment by MKhayle** [comment]
Should be fixed/done in https://github.com/MKhayle/XIVComboExpanded/commit/4a7ba95fc6e247ed4a2954bacd9a20cb6848b4ea
