### ISSUE TITLE
[Request] NIN: Bhavacakra to Hellfrog Medium Level Sync Feature

### ISSUE THREAD

**Issue by Angel2357** [MKhayle/XIVComboExpanded#442]
I've been levelling Ninja, but there's some jank at the current level that is exactly in this plugin's wheelhouse. Hellfrog Medium is acquired at 62, but Bhavacakra is level 68, leaving a window of six levels (which I believe encompasses twwwo dungeons? and a trial?) in which your only spender is Hellfrog Medium. 

As such, I'd love a feature for this similar to what Samurai does with Senei -> Guren for levels 70 and 71. Namely, at levels 62-67, replace Bhavacakra with Hellfrog Medium. This is definitely kind of niche, but getting jumpscared with Shisui of the Violet Tides and realizing your Ninki spender is somewhere else on your gamepad or keyboard doesn't sound fun.

**Comment by kaedys** [comment]
Ya, that makes sense as a level sync option.

**Comment by yurisim** [comment]
`
if (level >= NIN.Levels.HellfrogMedium && InMeleeRange() && ninki >= 50)
    return OriginalHook(level >= NIN.Levels.Bhavacakra ? NIN.Bhavacakra : NIN.HellfrogMedium);
`

This should work.
