### ISSUE TITLE
[Request] PCT: Hammer Holy Combo

### ISSUE THREAD

**Issue by Propagandist1** [MKhayle/XIVComboExpanded#444]
**Describe the feature you'd like**
Replace Holy in White with Hammer Brush and its combo chain when they are usable.

It seems like when you use Striking Muse and have Hammer Time charges, you'd probably want to use Hammer Brush over Holy in White or Comet in Black.  This feature would be similar in function to the Rainbow Holy Combo, replacing Holy in White with Hammer Brush when Hammer Time charges are present.  Recommend putting it as a sub-option under Holy Comet Combo, just like Rainbow Holy Combo.  

This would help consolidate some of the conditional instant-cast stuff onto the Holy in White button.

**Additional context**
Prior to hitting Striking Muse...
![image](https://github.com/user-attachments/assets/3e542006-a29e-47b0-b455-e1d83472d5ca)

After hitting Striking Muse!
![image](https://github.com/user-attachments/assets/d65afa58-5da7-463f-a788-c65e4ff461fc)
![image](https://github.com/user-attachments/assets/d7bf4247-9e16-4f08-bc7f-38f9e2fac8ed)

**Comment by kaedys** [comment]
Sure, that makes sense

**Comment by MKhayle** [comment]
Sorry for the time it took for me to get back to this plugin, I had a lot happening lately

**Comment by MKhayle** [comment]
This will be done soon

**Comment by MKhayle** [comment]
okay the soon was definitely a lie
