### ISSUE TITLE
[Request] [PLD] Shield Lob to Holy Spirit

### ISSUE THREAD

**Issue by Vec7rex** [MKhayle/XIVComboExpanded#445]
Replace Shield Lob with Holy Spirit while Divine Might Effect is active.

There is no reason to use a Shield Lob, instead a Holy Spirit does more damage under the Effect and also has no cast time.

**Comment by kaedys** [comment]
I admit I'm surprised we don't have this one already.  I actually had to go check, because I _do_ remember having something like that when I updated the Paladin combos, but it's just a level sync option.  I see zero reason not to have this, and it'll be quite easy to implement.

**Comment by Vec7rex** [comment]
Great - many thanks for the positive feedback!

**Comment by MKhayle** [comment]
I also thought we had something similar, will work on it

**Comment by MKhayle** [comment]
This has been added in 2.0.1.4 https://github.com/MKhayle/XIVComboExpanded/commit/88dabab27518069439145376dd94ea1e32a8caab
