### ISSUE TITLE
[Request] [SMN] Replace Demis with Astral Flow while summoned

### ISSUE THREAD

**Issue by sorayukimori** [MKhayle/XIVComboExpanded#446]
**Description**
Replaces the respective "Summon Titan/Ifrit/Garuda-Egi" with the Astral Flow move for that Egi while it is summoned, and/or all of them while Demi-Bahamut/Phoenix/Solar Bahamut are summoned.

I'm aware of Mountain Buster (Titan's Astral Flow) already having options for replacing Ruin during certain things, and that Enkindle is already used in other combos. 

It struck me as odd that Astral Flow wasn't given more options outside of Titan's Mountain Buster and that these would be an easy swapping option, since you wouldn't use be able to resummon that Egi until after you had resummoned Demi, Phoenix or Solar anyways.

**Comment by kaedys** [comment]
Solid idea, I like it
