### ISSUE TITLE
[Other] XLLog

### ISSUE THREAD

**Issue by RedactedFFXIV** [MKhayle/XIVComboExpanded#447]
![grafik](https://github.com/user-attachments/assets/86e0f82b-9522-4534-8b9d-d0115d502eed)

**Comment by MKhayle** [comment]
This shouldn't be happening, do you have any context?

**Comment by RedactedFFXIV** [comment]
That happens everytime I start FFXIV and log in or switch map etc.

**Comment by MKhayle** [comment]
I can't replicate this and have never seen this happening, may be some dalamud switcheroo, idk

Closing for now, but if you get that again please reopen this issue
