### ISSUE TITLE
[Request] AST seperate malefic/gravity to arcana

### ISSUE THREAD

**Issue by Chaotic-Sky** [MKhayle/XIVComboExpanded#448]
![image](https://github.com/user-attachments/assets/aeb6eb60-b311-4ead-bfa4-313b51b42402)
I would appreciate it if these could be separated, one option for Malefic and one option for Gravity. 

There are cases where you might want to hold onto Lord while spamming malefic (or presumably gravity) such as during the opener. But current implementation doesn't allow that as it overwrites both or neither, instead of _either_.

![image](https://github.com/user-attachments/assets/42f3e25d-d7e9-4768-90dd-1a3f39d34fde)

This makes the opener impossible with the option enabled since malefic is being replaced by Lord, but this could be easily fixed by having a option for Lord to only overwrite Gravity.

**Comment by MKhayle** [comment]
Looks reasonable, I'll check this out

**Comment by MKhayle** [comment]
Should be fixed/done in https://github.com/MKhayle/XIVComboExpanded/commit/4a7ba95fc6e247ed4a2954bacd9a20cb6848b4ea
