### ISSUE TITLE
[Bug]My plugin interface is incomplete

### ISSUE THREAD

**Issue by FelixQAQ777** [MKhayle/XIVComboExpanded#455]
The version is 2.0.0.12
![DB048736D6ADDA7FA9A5D07C4B13DE7B](https://github.com/user-attachments/assets/2744dd4b-30d2-48e8-9692-217dfa392270)

**Comment by warknight1211** [comment]
I see you closed this issue. Did you solve this problem? Can you tell me in detail how you solved this problem?
