### ISSUE TITLE
[Bug] VPR "PVP Style combos" when synced below 50

### ISSUE THREAD

**Issue by bluesolei1** [MKhayle/XIVComboExpanded#456]
**Describe the bug**
When using "PVP style combos" options, both aoe and ST, while level synced to <50, combo will get stuck at ability not yet learned.

**To Reproduce**

For aoe combo to break, queue into Stone Vigil synced. It syncs to level 43. Second step of aoe combo is Swiftskin's Bite which unlocks at 45, making combo button stuck

For ST combo to break, queue into Tam-Tara synced. It syncs to level 19. Second step of ST combo is Swiftskin's Sting which unlocks at 20, making combo button stuck

1. 2.0.0.12
2. VPR
3. Serpent's fang feature, Twincoil feature, Generation Legacy feature, All-in-one Reawaken feature, Uncoiled fury follow-up, Merge Twinfang/Twinblood into Serpent's Tail feature, all in pvp style combos

5. Steel Fangs, Steel Maw
6. Are you using any other XIVCombo fork? because you shouldn't - Nope

**Expected behavior**
I'd expect combo to wrap around once it reaches ability player cant use

**Additional context**
Possible workaround is to disable pvp  style combos if you get into sub 50 duty

**Comment by MKhayle** [comment]
Fixed in 2.0.1.1
