### ISSUE TITLE
[Bug] SAM: "Iaijutsu to Tsubame-gaeshi" nonfunctional

### ISSUE THREAD

**Issue by Angel2357** [MKhayle/XIVComboExpanded#458]
The feature is meant to replace Iaijutsu with Tsubame-gaeshi when it's usable. I am at the correct level to use Tsubame-gaeshi and am even able to use it when bound separately. However, Iaijutsu doesn't change, whether the Single-Sen option is ticked on or off.

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have: The last changelog I see is ver v2.0.0.12. If there's a higher version, I haven't been getting it.
2. Which job is affected: SAM, of course. 
3. What are your enabled combos for that job: Iaijutsu to Tsubame-gaeshi, Yukikaze Combo, Gekko Combo (+Gekko Combo Option), Kasha Combo (+Kasha Combo Option), Senei to Guren Level Sync
4. Which skill is placed in your hotbar: Both. And both are working as if the option wasn't turned on.
5. Are you using any other XIVCombo fork?: obviously not

**Expected behavior**
Well... Iaijutsu should be being replaced with Kaeshi Setsugekka et al after using Midare Setsugekka et al. 

**Screenshots or videos**
![ffxiv_dx11_uAhruxo7dX](https://github.com/user-attachments/assets/3a6c30ce-eb1f-415d-a0c5-d8adb66cdc33)

Note the Tsubame-gaeshi button in the upper left quadrant correctly lit up with Kaeshi Setsugekka. Meaning the combo is active. I've made sure that pressing the button actually executes the skill, too.

**Comment by MKhayle** [comment]
Hello, I haven't been able to replicate this issue at all on the current version. 
Please try again and keep me updated about it.

**Comment by Angel2357** [comment]
...that would be pretty difficult at the moment, considering Dalamud hasn't been updated for 7.1.

**Comment by Angel2357** [comment]
Now that  Dalamud has returned, I can confirm nothing about the feature has changed. I'm on version 2.0.1.1, the feature is not activating with everything looking and acting the same as on the original post. I'm using a gamepad, but even on a keyboard hotbar and activated via clicking, Iaijutsu does not turn into Tsubame-Gaeshi; I even paid attention to the Tsubame-Gaeshi button to see if it turned into Iaijutsu skills when you have Sen, in case it was doing it in reverse, but nothing.

Maybe this is related to the Tsubame-Gaeshi change. It no longer has a cooldown and instead operates on a Tsubame-Gaeshi proc since just a few patches ago, so there might be a misplaced trigger somewhere??

**Comment by MKhayle** [comment]
I'll dig into it but I haven't been able to replicate it so far

**Comment by MKhayle** [comment]
If you are level 74/75, I can fix it. The level check had not been updated with 7.05's learning level change and it was still at 76 instead of 74.

**Comment by Angel2357** [comment]
Oh, sorry for the late reply. I am indeed level 74, which would explain it. I'll try to pound out two more levels and see if the issue is corrected at 76.

**Comment by Angel2357** [comment]
Okay yeah, I got to level 76 and the feature is working entirely now. So it is indeed just the level flag. Thank you for taking a look.

**Comment by MKhayle** [comment]
It'll be fixed with the next version, thanks for the report!
