### ISSUE TITLE
[Bug]7.1 Issue: MCH "Hypercharge Feature"

### ISSUE THREAD

**Issue by ImRingo** [MKhayle/XIVComboExpanded#460]
I'm not sure if this is not just a greater Dalamud issue but at least with the "Hypercharge Feature" for MCH it is not working as intended (which is to turn "Hypercharge" into "Heatblast" and at later levels "Blazing Shot" once Hypercharge has been used and you have your stacks of "Overheated"). Right now, even when you turn on the "Hypercharge Feature", the "Hypercharge" ability is not turning into "Blazing Shot".

**Comment by ImRingo** [comment]
NVM saw your other bug report. My bad.

**Comment by MKhayle** [comment]
You should absolutely not be using Dalamud right now.

**Comment by ImRingo** [comment]
Why not? The plugin, other than this specific instance, is working more than fine. Same with a couple other custom repository plugins. No crashes what so ever yet.
