### ISSUE TITLE
[Bug] PCT Star Prism, NIN Forked Raiju

### ISSUE THREAD

**Issue by Ashiidia** [MKhayle/XIVComboExpanded#461]
**Describe the bug**
Star prism is replacing Landscape Motif instead of Starry Muse (PCT.LandscapeMotifDrawn) like it says in the description and in visual example next to the combo.

Aeolian Edge and Armor Crush are replaced with Fleeting Raiju (all 4 options are using same skill) instead of Forked Raiju like it says in the description and in visual example next to the combo.

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have - 2.0.1.1
2. Which job is affected - Pictomancer, Ninja
3. What are your enabled combos for that job - Landscape Muse/Star Prism Combo (PCT), Aeolian Edge / Forked Raiju Feature (NIN), Armor Crush / Forked Raiju Feature (NIN)
4. Which skill is placed in your hotbar - Scenic Muse, Aeolian Edge, Armor Crush
5. Are you using any other XIVCombo fork? - No

**Expected behavior**
Scenic Muse (Starry Sky) should be replaced with Star prism.
Aeolian Edge combo should be replaced with Forked Raiju.
Armor Crush combo should be replaced with Forked Raiju.

**Comment by MKhayle** [comment]
I'll check on that soon. Confirmed for all situations, thanks for the bug report!

**Comment by kaedys** [comment]
Hmm.  So, that's the intended behavior, as it stands.  While the combo states that it replaces Starry Muse with Star Prism (and the icons match that), the name of it is `Landscape Muse/Star Prism Combo`.  However, I don't think we necessarily _need_ for that to be the behavior.  We can probably make it like the other replacement-of-a-replacement combos, where it replaces Starry Muse, and then also replaces Landscape Muse if the Landscape Muse/Motif Combo immediately above it is also selected.  Anyone with both checked, it'll work exactly as it does now, and if someone prefers to keep the two separate, like the OP, selecting only the latter would provide that.

I can probably tackle that later tonight, @MKhayle

**Comment by MKhayle** [comment]
PCT's implementation was prior to the icons system and was the job I experienced with at first, and tbh PCT's motif/muses are a MESS to deal with, indeed 

Feel free to go for it

**Comment by Ashiidia** [comment]
That would be great, yes. I prefer having my "draw motif" buttons do only the long drawing and buff itself that gives star prism to change to star prism

The other problem is the name too, thats where confusion came from initially. Landscape muse isn't a thing, there's only Landscape Motif (drawing) and Scenic Muse (execution of drawing), so option would be Landscape motif + Star Prism combo

Obviously having both options is always better, thanks

**Comment by MKhayle** [comment]
Yeah, I'm playing on a french client and having not to mix up `motif`, `muse`, `imagi` and `picto` is super painful.
