### ISSUE TITLE
Does not work for Black Magic

### ISSUE THREAD

**Issue by onahool** [MKhayle/XIVComboExpanded#462]
**Describe the bug**
Nothing works except "Blizzard 1/3 Feature"

**To Reproduce**
1. v2.0.1.1
2. BlackMage
3.  Other than Blizzaga
4. so many
5. Not yet

**Expected behavior**
Selecting various items does not work
I can confirm that it works for non-black mages, but only black mages don't work.

**Screenshots or videos**
![6e93a62f31cf9afef7d6f62be773b867](https://github.com/user-attachments/assets/933d6a38-5b98-49bd-92ab-3a8f12945a87)

**Additional context**

**Comment by lhn1703** [comment]
Likely dalamud Client Structs issue, see #459.

**Comment by MKhayle** [comment]
I am not a Black Mage player, but it doesn't look like anything is broken at this point on my end. You may be using an oudated Dalamud version. I'm closing this issue for now, if you experience that issue again once Dalamud is publicly released, please reopen it.
Also, if you're not a developer, you shouldn't be using Dalamud right now but you do you.
