### ISSUE TITLE
[Bug] SMN: ES Painflare Feature not changing icon

### ISSUE THREAD

**Issue by Lapidearum** [MKhayle/XIVComboExpanded#463]
**Describe the bug**
The icon for Painflare is unchanged by the feature even when it should be replaced by Energy Siphon. It still _functions_ as Energy Siphon when applicable, so this is purely a visual error. 

**To Reproduce**
Enable the feature. Have Painflare bound to a hotbar.

**Expected behavior**
Painflare's icon and cooldown are supposed to be replaced by Energy Siphon's when an aetherflow stack with which to cast Painflare is not available.

**Additional context**
Energy Drain still works fully as intended; since it and Energy Siphon share a cooldown, this isn't a particularly impactful bug in practice. I figured I should report it nonetheless.

**Comment by MKhayle** [comment]
I can't replicate this issue.

**Comment by Lapidearum** [comment]
...Huh. I closed the game for unrelated reasons and then repoened it, and it's? Fine now? It works now. Issue's gone.

Weird. Well, I have no idea what could possibly have caused it on my end, but sorry for wasting your time!

**Comment by MKhayle** [comment]
You probably had an oudated Dalamud version, and it was a duplicate of #459 
Closing this issue since it's fixed!
