### ISSUE TITLE
[Bug] RPR - Automatic Soul Reaver

### ISSUE THREAD

**Issue by debonairdead** [MKhayle/XIVComboExpanded#469]
**Describe the bug**
Automatic Soul Reaver does not appear to function when Level Sync'd to 50, as experienced moments ago whilst in Lv50 Alliance Raid *World of Darkness*

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. XIV CE 2.0.1.1
2. Reaper
3. Slice Combo, Scythe Combo, Automatic Soul Reaver, Slice Gibbet, Soul Gibbet, Scythe Guillotine, Soul Reaver Enhanced, Reaping Enhanced, Reaping Lemure's, Enshroud Communio, Enshroud Perfectio, Arcane Harvest, 
4. ![image](https://github.com/user-attachments/assets/38a44522-2801-433e-b06b-3ef63e8ea9a2)
5. XIV CE 2.0.1.1

**Comment by MKhayle** [comment]
@kaedys wasn't that supposed to be fixed

**Comment by kaedys** [comment]
Ah.  I may have accidentally used `>` instead of `>=` when doing the level check on those >.>  Uno momento
