### ISSUE TITLE
[Request] SAM - Oka integration into Fuga > Mangetsu rotation depending on Fuka state

### ISSUE THREAD

**Issue by baelrayneVessdren** [MKhayle/XIVComboExpanded#472]
**Describe the feature you'd like**
Hi Combo-Team.

First of all: Many thanks for your hard and dedicated work on this wonderful plugin. 

I'd like to know if it is possible to integrate Oka into the basic Fuga > Mangetsu rotation to either a) keep up Fuka if below x seconds remaining (coming from single target rotation using Shifu) or b) grant Fuka if not up. 

Thanks a lot.

**Comment by kaedys** [comment]
Erm... Fuga -> Mangetsu isn't an AoE rotation for Sam.  The standard SAM AoE rotation is uses _both_ Mangetsu and Oka to generate the relevant Sen, then Iaijutsu to use Tenka Goken.  Just spamming Fuga -> Mangetsu repeatedly will do wildly less damage than that.

That said, we could _probably_ justify a secret combo that makes both Oka and Mangetsu auto-swap to each other depending on which Sen you're missing.

**Comment by baelrayneVessdren** [comment]
Probably should have written combo. And thanks for the additional information. I was not aware that the AoE chain builds Sen (should have though since any other AoE chain build resources as well). My SAM is still level 50 with glorious 0 EXP. I was just testing out the several abilities and found it strange, that there was no such feature. Mostly playing WAR and it reminded me of the overcap protection. Or VPR's Tail / Fang swaps.

The auto swap is really all I would and could ask for. Thank you very much for considering it.

**Comment by kaedys** [comment]
@MKhayle you can assign this one to me, I've started tackling it locally.

**Comment by kaedys** [comment]
Ok, @baelrayneVessdren, added 3 new combos.  One simply makes Oka turn into Mangetsu if you already have the Ka Sen and not the Getsu Sen, and vice versa, with no other logic.  I also added two sub-combos for it, one that makes Oka and Mangetsu swap to whichever has the lowest buff time remaining when you have neither Sen, and one that swaps both to Tenka Goken (and, if the Iaijutsu to Tsubame feature is selected, also Kaeshi Goken) if you have both Sen.

**Comment by MKhayle** [comment]
I didnt even have time finishing sleeping and you had already completed it wtf.

**Comment by kaedys** [comment]
Had just finished an 8-hour drive back from my sister's and was a bit wired and in need of something thinky to do.

**Comment by baelrayneVessdren** [comment]
> Ok, @baelrayneVessdren, added 3 new combos. One simply makes Oka turn into Mangetsu if you already have the Ka Sen and not the Getsu Sen, and vice versa, with no other logic. I also added two sub-combos for it, one that makes Oka and Mangetsu swap to whichever has the lowest buff time remaining when you have neither Sen, and one that swaps both to Tenka Goken (and, if the Iaijutsu to Tsubame feature is selected, also Kaeshi Goken) if you have both Sen.

That is even more than I had originally in mind. Thanks a lot for the additional work and expanding on the request.

**Comment by kaedys** [comment]
Ya, I figured while I was at it, might as well.  This _should_ now let you just have a single button AoE combo for most or all use-cases, I believe.
