### ISSUE TITLE
[Other] Update MyDalamudPlugins

### ISSUE THREAD

**Issue by lhn1703** [MKhayle/XIVComboExpanded#477]
I noticed Daemitus's repo not being updated for a while. What's the typical code release schedule? https://github.com/daemitus/MyDalamudPlugins/tree/master/plugins

**Comment by MKhayle** [comment]
I'll probably push a version tomorrow

**Comment by MKhayle** [comment]
(it was again: a lie, but it's been done with https://github.com/MKhayle/XIVComboExpanded/commit/d0ae94c0ac6f8ff47365b2f568db4555a3591aa1 's v2.0.1.2
