### ISSUE TITLE
[Bug] Fan Dance 3 Feature Not Working

### ISSUE THREAD

**Issue by SilvaLau** [MKhayle/XIVComboExpanded#478]
**Describe the bug**
Fan Dance 3 Feature and Flourishing Fan Dance 4 for DNC is not working.

**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have: 2.0.1.1
2. Which job is affected: DNC
3. What are your enabled combos for that job: Single Target to Procs, AoE Procs, Automatic Saber Dance, Single-Target 85 Esprit, Single-Target 50 Esprit in Tech Step, **Fan Dance 3 Feature**, **Flourishing Fan Dance 4**, Last Dance Feature, Dance Step Combo
4. Which skill is placed in your hotbar: Fan Dance, Fan Dance II, Fan Dance III, Fan Dance IV, Flourish
5. Are you using any other XIVCombo fork? because you shouldn't: No

**Expected behavior**
Fan Dance & Fan Dance II should be replaced by Fan Dance III when it triggers
Flourish should be replaced by Fan Dance IV when it triggers

**Screenshots or videos**
![image](https://github.com/user-attachments/assets/89e708ed-62d6-43a6-96a0-07f0922b9925)

**Additional context**

**Comment by SilvaLau** [comment]
oh I just realized Flourishing Fan Dance 4 is not working either

**Comment by MKhayle** [comment]
I can't reproduce your issue. Fan Dance 3 Feature works fine on my end, even with the exact same setup (controller aside). Flourishing Fan Dance 4 also works for me.

**Comment by SilvaLau** [comment]
Seems fixed after a quick relog, must be a graphical thing. Sorry for the cause for concern.
