### ISSUE TITLE
[Other] Revert Oka/Mangetsu Changes? (Samurai)

### ISSUE THREAD

**Issue by Rietty** [MKhayle/XIVComboExpanded#483]
Hi! So I'm not sure if I'm going crazy but previously there seemed to be an option to do Fuko -> Oka and Fuko -> Mangetsu separately, but for some reason they got rolled into one button/option now? I'm asking if this can be reverted or just allow the option to do these individually as I only want to enable it for one, but not the other.

**Comment by MKhayle** [comment]
@kaedys We could re-add them as options I guess?

**Comment by MKhayle** [comment]
I don't remember we had separate options, though but I'll look into it anyway

**Comment by Rietty** [comment]
Just looking through the changes it seems they were changed here to a generalized SAM AoE Combo? https://github.com/MKhayle/XIVComboExpanded/commit/964b424e4127200a804f993ccc790d74a80c93c6

**Comment by MKhayle** [comment]
Oh well, merry christmas @kaedys (if you don't fix it I'll do it)

**Comment by kaedys** [comment]
They were combined into the same option, because frankly, I didn't see why anyone would want one of the two to auto-swap and not the other.  What's the use-case for them being separated like that?

**Comment by Rietty** [comment]
Because the way I did AoE is I managed the Sen individually and only used one of the two options to distinct which Sen I'm building when I'm AoEing. So I would press the button to do either: Fuko -> Mangetsu or I would press the Fuko -> Mangetsu button but then use Oka manually instead. 

It also got rid of the confusion of which key does what, and preventing duplicates on the hot bar which frankly looks weird as hell. 

It is also a bit weird to just unilaterally decide to remove the old stuff instead of simply adding on a smart AoE combo instead.

Regardless I would very much appreciate it being put back.

**Comment by kaedys** [comment]
I'll have to fiddle with the code and get it split back up after the holidays.  I should be able to tackle this when I'm back home somewhere around New Years.  Fortunately, the old combo ID is still available, since we don't really ever re-use those, so once I re-add it, it should just auto-acquire your prior setting for the feature.

**Comment by Rietty** [comment]
Thank you very much!

**Comment by MKhayle** [comment]
I see that option equivalent to the options for Shifu and the other one (Hakaze?) because there are some people who dislike seeing twice the same button on their hotbar so that's honestly fair. I'll see if I have time for this before NY

**Comment by kaedys** [comment]
For Shifu, I figured it was separate between the combos are different length, and we also have a secondary option to only start the combo on the 2nd hit instead of the 1st one.  But ya, it shouldn't be _too_ tough to open it back up, I don't think.

**Comment by MKhayle** [comment]
> I don't think.

Yeah, me neither.

**Comment by MKhayle** [comment]
I took care of it, will be soon live

**Comment by MKhayle** [comment]
Should be fixed/done in https://github.com/MKhayle/XIVComboExpanded/commit/4a7ba95fc6e247ed4a2954bacd9a20cb6848b4ea
